name = "idealab-premium"
main = "worker/index-free-auth-bootstrap.ts"
compatibility_date = "2026-08-01"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
binding = "ASSETS"
run_worker_first = [ "/api/*" ]

[[d1_databases]]
binding = "DB"
database_name = "idealab-crm"
database_id = "023c6004-fb3a-41d4-8c4f-bccf51409fae"

[vars]
SUPER_ADMIN_EMAIL = "nawazidealab@gmail.com"
ADMIN_PASSWORD_SALT = "75a94442822c89d67fb99355bfd2bb5c"
ADMIN_PASSWORD_HASH = "02a88e9b4e3d576c18abc4e77b7dc3e846e05551b5eaed2053d803d1b3e60ec0"
ALLOWED_ORIGINS = ""
