import app from './index-users-delete-v18';

interface Env{DB:D1Database;SUPER_ADMIN_EMAIL:string;ADMIN_PASSWORD_SALT:string;ADMIN_PASSWORD_HASH:string;ALLOWED_ORIGINS?:string}
type Role='super_admin'|'admin'|'sales'|'project_manager'|'finance'|'content';
type Identity={id:number;name:string;email:string;role:Role;active:number};
type Access={chat:number;all_clients:number};
type Channel={type:'general'|'client'|'dm'|'space';targetId:number|null;key:string};
const SESSION_COOKIE='idealab_admin_session';
let ready=false;

function json(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store, max-age=0','x-content-type-options':'nosniff','x-idealab-collab':'v19'}})}
function hex(bytes:Uint8Array){return Array.from(bytes,v=>v.toString(16).padStart(2,'0')).join('')}
async function sha(value:string){return hex(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value))))}
function cookie(req:Request,name:string){for(const part of (req.headers.get('cookie')||'').split(';')){const[k,...r]=part.trim().split('=');if(k===name)return decodeURIComponent(r.join('='))}return null}
function clean(value:unknown,max=1500){if(typeof value!=='string')return null;const x=value.trim();return x&&x.length<=max?x:null}
function id(value:unknown){const n=Number(value);return Number.isInteger(n)&&n>0?n:null}
function safeColor(value:unknown){const x=typeof value==='string'?value.trim():'';return /^#[0-9a-f]{6}$/i.test(x)?x:'#6d5dfc'}
function safeIcon(value:unknown){const x=typeof value==='string'?value.trim().slice(0,8):'';return x||'💬'}
function safeAvatar(value:unknown){if(typeof value!=='string'||!value.trim())return null;try{const u=new URL(value.trim());return u.protocol==='https:'&&u.href.length<=600?u.href:null}catch{return null}}
function requireWrite(req:Request){const u=new URL(req.url);if(req.headers.get('origin')!==u.origin||req.headers.get('x-requested-with')!=='idealab-admin'||!(req.headers.get('content-type')||'').toLowerCase().startsWith('application/json'))throw new Error('write')}
async function actor(req:Request,env:Env):Promise<Identity>{const token=cookie(req,SESSION_COOKIE);if(!token)throw new Error('auth');const row=await env.DB.prepare(`SELECT u.id,u.name,u.email,u.role,u.active,s.expires_at FROM admin_sessions s JOIN users u ON u.id=s.user_id WHERE s.session_hash=? LIMIT 1`).bind(await sha(token)).first<any>();if(!row||!row.active||Number(row.expires_at)<=Math.floor(Date.now()/1000))throw new Error('auth');return{id:Number(row.id),name:String(row.name),email:String(row.email),role:row.role as Role,active:Number(row.active)}}
async function access(env:Env,u:Identity):Promise<Access>{if(u.role==='super_admin')return{chat:1,all_clients:1};const r=await env.DB.prepare('SELECT chat,all_clients FROM user_access WHERE user_id=? LIMIT 1').bind(u.id).first<any>();return{chat:r?Number(r.chat):1,all_clients:r?Number(r.all_clients):1}}
async function addColumn(env:Env,table:string,column:string,definition:string){const r=await env.DB.prepare(`PRAGMA table_info(${table})`).all<{name:string}>();if(!(r.results||[]).some(c=>String(c.name)===column))await env.DB.prepare(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`).run()}
async function schema(env:Env){if(ready)return;await addColumn(env,'users','avatar_url','TEXT');await addColumn(env,'users','profile_icon','TEXT');await addColumn(env,'users','profile_color','TEXT');await addColumn(env,'chat_messages','space_id','INTEGER');await addColumn(env,'chat_messages','reply_to_id','INTEGER');await env.DB.prepare(`CREATE TABLE IF NOT EXISTS chat_spaces(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,description TEXT,icon TEXT NOT NULL DEFAULT '💬',color TEXT NOT NULL DEFAULT '#6d5dfc',created_by INTEGER NOT NULL,archived INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();await env.DB.prepare(`CREATE TABLE IF NOT EXISTS chat_space_members(space_id INTEGER NOT NULL,user_id INTEGER NOT NULL,added_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(space_id,user_id))`).run();await env.DB.prepare(`CREATE TABLE IF NOT EXISTS chat_mentions(message_id INTEGER NOT NULL,user_id INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(message_id,user_id))`).run();await env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_chat_space_id ON chat_messages(space_id,id)').run();await env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_chat_reply ON chat_messages(reply_to_id)').run();await env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_chat_mentions_user ON chat_mentions(user_id,message_id)').run();await env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_chat_space_members_user ON chat_space_members(user_id,space_id)').run();ready=true}
function parse(raw:string|null):Channel|null{const v=(raw||'general').trim();if(v==='general')return{type:'general',targetId:null,key:'general'};const m=/^(client|dm|space):(\d+)$/.exec(v);if(!m)return null;return{type:m[1] as Channel['type'],targetId:Number(m[2]),key:v}}
async function allowed(env:Env,u:Identity,a:Access,c:Channel){if(c.type==='general')return true;if(c.type==='dm')return c.targetId!==u.id&&!!(await env.DB.prepare('SELECT id FROM users WHERE id=? AND active=1 LIMIT 1').bind(c.targetId).first());if(c.type==='client'){if(u.role==='super_admin'||a.all_clients!==0)return !!(await env.DB.prepare('SELECT id FROM clients WHERE id=? LIMIT 1').bind(c.targetId).first());return !!(await env.DB.prepare('SELECT 1 ok FROM user_client_access WHERE user_id=? AND client_id=? LIMIT 1').bind(u.id,c.targetId).first())}return u.role==='super_admin'||!!(await env.DB.prepare('SELECT 1 ok FROM chat_space_members WHERE space_id=? AND user_id=? LIMIT 1').bind(c.targetId,u.id).first())}
function profileRow(r:any){return{id:Number(r.id),name:String(r.name),email:r.email?String(r.email):undefined,role:String(r.role||'team'),avatar_url:r.avatar_url?String(r.avatar_url):null,profile_icon:r.profile_icon?String(r.profile_icon):null,profile_color:r.profile_color?String(r.profile_color):'#6d5dfc'}}

async function bootstrap(req:Request,env:Env,u:Identity,a:Access){const legacyUrl=new URL(req.url);legacyUrl.pathname='/api/chat-v2/conversations';legacyUrl.search='';const legacyRes=await app.fetch(new Request(legacyUrl.toString(),{method:'GET',headers:req.headers}),env);if(!legacyRes.ok)return legacyRes;const legacy=await legacyRes.json() as any;const people=(await env.DB.prepare('SELECT id,name,email,role,avatar_url,profile_icon,profile_color FROM users WHERE active=1 ORDER BY name ASC').all<any>()).results||[];const map=new Map<number,any>(people.map((p:any)=>[Number(p.id),p]));const base=(legacy.results||[]).map((c:any)=>{const p=c.type==='dm'?map.get(Number(c.target_id)):null;return{...c,avatar_url:p?.avatar_url||null,profile_icon:p?.profile_icon||null,profile_color:p?.profile_color||null}});
 const spaces=(u.role==='super_admin'?(await env.DB.prepare(`SELECT s.*,COUNT(sm.user_id) member_count FROM chat_spaces s LEFT JOIN chat_space_members sm ON sm.space_id=s.id WHERE s.archived=0 GROUP BY s.id ORDER BY s.name`).all<any>()):(await env.DB.prepare(`SELECT s.*,COUNT(allm.user_id) member_count FROM chat_spaces s JOIN chat_space_members mine ON mine.space_id=s.id AND mine.user_id=? LEFT JOIN chat_space_members allm ON allm.space_id=s.id WHERE s.archived=0 GROUP BY s.id ORDER BY s.name`).bind(u.id).all<any>())).results||[];
 const readRows=(await env.DB.prepare(`SELECT channel_key,last_message_id FROM chat_reads WHERE user_id=? AND channel_key LIKE 'space:%'`).bind(u.id).all<any>()).results||[];const reads=new Map(readRows.map((r:any)=>[String(r.channel_key),Number(r.last_message_id||0)]));
 const lastRows=(await env.DB.prepare(`SELECT m.space_id,m.id,m.message,m.created_at,u.name user_name FROM chat_messages m JOIN users u ON u.id=m.user_id JOIN(SELECT space_id,MAX(id) max_id FROM chat_messages WHERE space_id IS NOT NULL GROUP BY space_id)x ON x.max_id=m.id`).all<any>()).results||[];const last=new Map(lastRows.map((r:any)=>[Number(r.space_id),r]));
 const unreadRows=(await env.DB.prepare(`SELECT m.space_id,COUNT(*) count FROM chat_messages m LEFT JOIN chat_reads r ON r.user_id=? AND r.channel_key=('space:'||m.space_id) WHERE m.space_id IS NOT NULL AND m.user_id<>? AND m.id>COALESCE(r.last_message_id,0) GROUP BY m.space_id`).bind(u.id,u.id).all<any>()).results||[];const unread=new Map(unreadRows.map((r:any)=>[Number(r.space_id),Number(r.count||0)]));
 for(const s of spaces){const sid=Number(s.id),l=last.get(sid);base.push({key:`space:${sid}`,type:'space',target_id:sid,title:String(s.name),subtitle:String(s.description||`${Number(s.member_count||0)} members`),avatar:String(s.icon||'💬'),profile_icon:String(s.icon||'💬'),profile_color:String(s.color||'#6d5dfc'),avatar_url:null,last_message:l?.message||'',last_at:l?.created_at||null,last_sender:l?.user_name||null,unread:unread.get(sid)||0,member_count:Number(s.member_count||0),created_by:Number(s.created_by)})}
 base.sort((x:any,y:any)=>{if(x.key==='general')return-1;if(y.key==='general')return 1;const xt=x.last_at?new Date(x.last_at).getTime():0,yt=y.last_at?new Date(y.last_at).getTime():0;return yt-xt||String(x.title).localeCompare(String(y.title))});const me=map.get(u.id)||u;return json({results:base,total_unread:base.reduce((n:number,c:any)=>n+Number(c.unread||0),0),people:people.map(profileRow),me:profileRow(me),capabilities:{spaces:true,mentions:true,replies:true,profiles:true}})}

function whereFor(c:Channel,u:Identity){if(c.type==='general')return{sql:'m.client_id IS NULL AND m.recipient_user_id IS NULL AND m.space_id IS NULL',bind:[] as unknown[]};if(c.type==='client')return{sql:'m.client_id=? AND m.recipient_user_id IS NULL AND m.space_id IS NULL',bind:[c.targetId] as unknown[]};if(c.type==='space')return{sql:'m.space_id=?',bind:[c.targetId] as unknown[]};return{sql:'m.client_id IS NULL AND m.space_id IS NULL AND ((m.user_id=? AND m.recipient_user_id=?) OR (m.user_id=? AND m.recipient_user_id=?))',bind:[u.id,c.targetId,c.targetId,u.id] as unknown[]}}
async function messageRows(env:Env,u:Identity,c:Channel,after:number,limit:number){const w=whereFor(c,u);const fields=`m.id,m.user_id,m.client_id,m.recipient_user_id,m.space_id,m.reply_to_id,m.message,m.created_at,u.name user_name,u.role user_role,u.avatar_url,u.profile_icon,u.profile_color,rm.message reply_message,rm.user_id reply_user_id,ru.name reply_user_name`;let q:string;let binds:unknown[];if(after>0){q=`SELECT ${fields} FROM chat_messages m JOIN users u ON u.id=m.user_id LEFT JOIN chat_messages rm ON rm.id=m.reply_to_id LEFT JOIN users ru ON ru.id=rm.user_id WHERE ${w.sql} AND m.id>? ORDER BY m.id ASC LIMIT ?`;binds=[...w.bind,after,limit]}else{q=`SELECT ${fields} FROM chat_messages m JOIN users u ON u.id=m.user_id LEFT JOIN chat_messages rm ON rm.id=m.reply_to_id LEFT JOIN users ru ON ru.id=rm.user_id WHERE ${w.sql} ORDER BY m.id DESC LIMIT ?`;binds=[...w.bind,limit]}const rows=(await env.DB.prepare(q).bind(...binds).all<any>()).results||[];return after>0?rows:[...rows].reverse()}
async function getMessages(req:Request,env:Env,u:Identity,a:Access){const url=new URL(req.url),c=parse(url.searchParams.get('channel'));if(!c||!(await allowed(env,u,a,c)))return json({error:'Conversation unavailable'},403);const after=Math.max(0,Number(url.searchParams.get('after_id')||0)||0),limit=Math.min(100,Math.max(1,Number(url.searchParams.get('limit')||70)||70));return json({results:await messageRows(env,u,c,after,limit),channel:c.key})}
async function send(req:Request,env:Env,u:Identity,a:Access){try{requireWrite(req)}catch{return json({error:'Invalid request'},403)}const b=await req.json().catch(()=>null) as any,c=parse(String(b?.channel||'general')),message=clean(b?.message);if(!b||!c||!message)return json({error:'A valid conversation and message are required'},400);if(!(await allowed(env,u,a,c)))return json({error:'Conversation unavailable'},403);const reply=id(b.reply_to_id);if(reply){const w=whereFor(c,u);if(!(await env.DB.prepare(`SELECT m.id FROM chat_messages m WHERE ${w.sql} AND m.id=? LIMIT 1`).bind(...w.bind,reply).first()))return json({error:'Reply target is not in this conversation'},400)}const clientId=c.type==='client'?c.targetId:null,recipientId=c.type==='dm'?c.targetId:null,spaceId=c.type==='space'?c.targetId:null;const result=await env.DB.prepare('INSERT INTO chat_messages(user_id,client_id,recipient_user_id,space_id,reply_to_id,message) VALUES(?,?,?,?,?,?)').bind(u.id,clientId,recipientId,spaceId,reply,message).run();const mid=Number(result.meta.last_row_id||0);const mentions=Array.isArray(b.mention_user_ids)?[...new Set(b.mention_user_ids.map(id).filter(Boolean))] as number[]:[];for(const uid of mentions.slice(0,20)){if(await env.DB.prepare('SELECT id FROM users WHERE id=? AND active=1 LIMIT 1').bind(uid).first())await env.DB.prepare('INSERT OR IGNORE INTO chat_mentions(message_id,user_id) VALUES(?,?)').bind(mid,uid).run()}await env.DB.prepare(`INSERT INTO chat_reads(user_id,channel_key,last_message_id,updated_at) VALUES(?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(user_id,channel_key) DO UPDATE SET last_message_id=MAX(chat_reads.last_message_id,excluded.last_message_id),updated_at=CURRENT_TIMESTAMP`).bind(u.id,c.key,mid).run();const row=(await messageRows(env,u,c,mid-1,1))[0];return json({ok:true,message:row},201)}
async function read(req:Request,env:Env,u:Identity,a:Access){try{requireWrite(req)}catch{return json({error:'Invalid request'},403)}const b=await req.json().catch(()=>null) as any,c=parse(String(b?.channel||''));if(!c||!(await allowed(env,u,a,c)))return json({error:'Invalid conversation'},400);const last=Math.max(0,Number(b?.last_message_id||0)||0);await env.DB.prepare(`INSERT INTO chat_reads(user_id,channel_key,last_message_id,updated_at) VALUES(?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(user_id,channel_key) DO UPDATE SET last_message_id=MAX(chat_reads.last_message_id,excluded.last_message_id),updated_at=CURRENT_TIMESTAMP`).bind(u.id,c.key,last).run();return json({ok:true})}

async function createSpace(req:Request,env:Env,u:Identity){try{requireWrite(req)}catch{return json({error:'Invalid request'},403)}const b=await req.json().catch(()=>null) as any,name=clean(b?.name,80);if(!name)return json({error:'Space name is required'},400);const description=clean(b?.description,220)||'',icon=safeIcon(b?.icon),color=safeColor(b?.color);const r=await env.DB.prepare('INSERT INTO chat_spaces(name,description,icon,color,created_by) VALUES(?,?,?,?,?)').bind(name,description,icon,color,u.id).run();const sid=Number(r.meta.last_row_id||0);const members=[...new Set([u.id,...(Array.isArray(b?.member_ids)?b.member_ids.map(id).filter(Boolean):[])])] as number[];for(const uid of members){if(await env.DB.prepare('SELECT id FROM users WHERE id=? AND active=1 LIMIT 1').bind(uid).first())await env.DB.prepare('INSERT OR IGNORE INTO chat_space_members(space_id,user_id) VALUES(?,?)').bind(sid,uid).run()}return json({ok:true,id:sid},201)}
async function patchSpace(req:Request,env:Env,u:Identity,sid:number){try{requireWrite(req)}catch{return json({error:'Invalid request'},403)}const s=await env.DB.prepare('SELECT id,created_by FROM chat_spaces WHERE id=? LIMIT 1').bind(sid).first<any>();if(!s)return json({error:'Space not found'},404);if(u.role!=='super_admin'&&Number(s.created_by)!==u.id)return json({error:'Only the space owner or Super Admin can edit this space'},403);const b=await req.json().catch(()=>null) as any;if(!b)return json({error:'Invalid JSON'},400);const fields:string[]=[],vals:unknown[]=[];if(b.name!==undefined){const v=clean(b.name,80);if(!v)return json({error:'Invalid name'},400);fields.push('name=?');vals.push(v)}if(b.description!==undefined){fields.push('description=?');vals.push(clean(b.description,220)||'')}if(b.icon!==undefined){fields.push('icon=?');vals.push(safeIcon(b.icon))}if(b.color!==undefined){fields.push('color=?');vals.push(safeColor(b.color))}if(fields.length)await env.DB.prepare(`UPDATE chat_spaces SET ${fields.join(',')},updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(...vals,sid).run();if(Array.isArray(b.member_ids)){await env.DB.prepare('DELETE FROM chat_space_members WHERE space_id=?').bind(sid).run();const members=[...new Set([Number(s.created_by),...b.member_ids.map(id).filter(Boolean)])] as number[];for(const uid of members)await env.DB.prepare('INSERT OR IGNORE INTO chat_space_members(space_id,user_id) SELECT ?,id FROM users WHERE id=? AND active=1').bind(sid,uid).run()}return json({ok:true})}
async function deleteSpace(req:Request,env:Env,u:Identity,sid:number){try{requireWrite(req)}catch{return json({error:'Invalid request'},403)}if(u.role!=='super_admin')return json({error:'Super Admin access required'},403);await env.DB.prepare('DELETE FROM chat_mentions WHERE message_id IN(SELECT id FROM chat_messages WHERE space_id=?)').bind(sid).run();await env.DB.prepare("DELETE FROM chat_reads WHERE channel_key=?").bind(`space:${sid}`).run();await env.DB.prepare('DELETE FROM chat_messages WHERE space_id=?').bind(sid).run();await env.DB.prepare('DELETE FROM chat_space_members WHERE space_id=?').bind(sid).run();await env.DB.prepare('DELETE FROM chat_spaces WHERE id=?').bind(sid).run();return json({ok:true})}

async function getProfile(env:Env,uid:number){const r=await env.DB.prepare('SELECT id,name,email,role,avatar_url,profile_icon,profile_color FROM users WHERE id=? LIMIT 1').bind(uid).first<any>();return r?profileRow(r):null}
async function patchProfile(req:Request,env:Env,u:Identity,uid:number){try{requireWrite(req)}catch{return json({error:'Invalid request'},403)}if(uid!==u.id&&u.role!=='super_admin')return json({error:'Super Admin access required'},403);const b=await req.json().catch(()=>null) as any;if(!b)return json({error:'Invalid JSON'},400);const fields:string[]=[],vals:unknown[]=[];if(b.name!==undefined){const v=clean(b.name,120);if(!v)return json({error:'Name must be at least 1 character'},400);fields.push('name=?');vals.push(v)}if(b.avatar_url!==undefined){const raw=typeof b.avatar_url==='string'?b.avatar_url.trim():'';const v=raw?safeAvatar(raw):null;if(raw&&!v)return json({error:'Profile photo must use a valid HTTPS URL'},400);fields.push('avatar_url=?');vals.push(v)}if(b.profile_icon!==undefined){fields.push('profile_icon=?');vals.push(safeIcon(b.profile_icon))}if(b.profile_color!==undefined){fields.push('profile_color=?');vals.push(safeColor(b.profile_color))}if(fields.length)await env.DB.prepare(`UPDATE users SET ${fields.join(',')},updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(...vals,uid).run();return json({ok:true,profile:await getProfile(env,uid)})}

export default{async fetch(req:Request,env:Env):Promise<Response>{const url=new URL(req.url),path=url.pathname;if(!path.startsWith('/api/chat-v3')&&!path.startsWith('/api/profile'))return app.fetch(req,env);let u:Identity;try{u=await actor(req,env)}catch{return json({error:'Sign in required'},401)}await schema(env);const a=await access(env,u);if(path.startsWith('/api/chat-v3')&&a.chat===0)return json({error:'Chat access is disabled for this account'},403);
 if(path==='/api/chat-v3/bootstrap'&&req.method==='GET')return bootstrap(req,env,u,a);
 if(path==='/api/chat-v3/messages'&&req.method==='GET')return getMessages(req,env,u,a);
 if(path==='/api/chat-v3/messages'&&req.method==='POST')return send(req,env,u,a);
 if(path==='/api/chat-v3/read'&&req.method==='POST')return read(req,env,u,a);
 if(path==='/api/chat-v3/spaces'&&req.method==='POST')return createSpace(req,env,u);
 const sm=/^\/api\/chat-v3\/spaces\/(\d+)$/.exec(path);if(sm&&req.method==='PATCH')return patchSpace(req,env,u,Number(sm[1]));if(sm&&req.method==='DELETE')return deleteSpace(req,env,u,Number(sm[1]));
 if(path==='/api/profile/me'&&req.method==='GET')return json({profile:await getProfile(env,u.id)});if(path==='/api/profile/me'&&req.method==='PATCH')return patchProfile(req,env,u,u.id);
 if(path==='/api/profile/users'&&req.method==='GET'){if(u.role!=='super_admin')return json({error:'Super Admin access required'},403);const rows=(await env.DB.prepare('SELECT id,name,email,role,avatar_url,profile_icon,profile_color,active FROM users ORDER BY active DESC,name ASC').all<any>()).results||[];return json({results:rows.map(profileRow)})}
 const pm=/^\/api\/profile\/users\/(\d+)$/.exec(path);if(pm&&req.method==='PATCH')return patchProfile(req,env,u,Number(pm[1]));return json({error:'Method not allowed'},405)}} satisfies ExportedHandler<Env>;
