import React,{useEffect,useMemo,useState,type ReactNode}from'react';
import{CircleAlert,Plus,RefreshCw,Search,Trash2,WalletCards}from'lucide-react';
import{adminApi,type D1Result}from'./admin-api';
import{CURRENCIES,CURRENCY_EVENT,convertMoney,formatCurrencyTotals,formatMoney,getDefaultCurrency,groupCurrencyTotals,type FxRates}from'./currencies';
import{useEnterprisePortal}from'./admin-enterprise-v17';
import'./admin-enterprise-finance-v18.css';

type Client={id:number;name:string};
type Invoice={id:number;client_id:number;client_name?:string;invoice_no:string;status:string;amount:number;currency:string;due_date:string|null;paid_at?:string|null};
type Report={leadStatus:Array<{status:string;count:number}>;clientStatus:Array<{status:string;count:number}>;projectStatus:Array<{status:string;count:number}>;taskStatus:Array<{status:string;count:number}>;invoiceStatus:Array<{status:string;count:number;total:number}>;contentStatus:Array<{status:string;count:number}>;overdueTasks:number;outstandingAmount:number;recentActivities:Array<any>};
type FxPayload={base:string;rates:FxRates;updatedAt:number|null;source:string};
const INVOICE_STATUS=['draft','sent','due','paid','void'];

function label(value:string){return value.replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase())}
function prettyDate(value:string){const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleDateString([],{month:'short',day:'numeric',year:d.getFullYear()!==new Date().getFullYear()?'numeric':undefined})}
function prettyDateTime(value:string){const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleString([],{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}

function useDisplayCurrency(){
 const[currency,setCurrency]=useState(getDefaultCurrency());
 useEffect(()=>{const sync=()=>setCurrency(getDefaultCurrency());window.addEventListener(CURRENCY_EVENT,sync);window.addEventListener('storage',sync);return()=>{window.removeEventListener(CURRENCY_EVENT,sync);window.removeEventListener('storage',sync)}},[]);
 return currency;
}

function convertedTotal(rows:Invoice[],target:string,rates?:FxRates|null){
 let total=0;
 for(const row of rows){const next=convertMoney(Number(row.amount||0),row.currency||'USD',target,rates);if(next===null||!Number.isFinite(next))return null;total+=next}
 return total;
}

export function InvoicesPageV18(){
 const{isSuper,notify}=useEnterprisePortal();
 const displayCurrency=useDisplayCurrency();
 const[rows,setRows]=useState<Invoice[]>([]),[clients,setClients]=useState<Client[]>([]),[rates,setRates]=useState<FxPayload|null>(null),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const[form,setForm]=useState({client_id:'',invoice_no:'',status:'draft',currency:getDefaultCurrency(),due_date:'',notes:'',description:'Professional services',quantity:'1',unit_price:''});
 const load=async()=>{setLoading(true);setError('');try{const settled=await Promise.allSettled([adminApi<D1Result<Invoice>>('/api/invoices'),adminApi<D1Result<Client>>('/api/clients'),adminApi<FxPayload>('/api/fx')]);if(settled[0].status==='rejected')throw settled[0].reason;setRows(settled[0].value.results||[]);if(settled[1].status==='fulfilled')setClients(settled[1].value.results||[]);if(settled[2].status==='fulfilled')setRates(settled[2].value)}catch(e){setError(e instanceof Error?e.message:'Unable to load invoices')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>rows.filter(r=>(status==='all'||r.status===status)&&Object.values(r).join(' ').toLowerCase().includes(query.toLowerCase())),[rows,status,query]);
 const outstanding=useMemo(()=>filtered.filter(i=>['sent','due'].includes(i.status)),[filtered]);
 const displayTotal=useMemo(()=>convertedTotal(outstanding,displayCurrency,rates?.rates),[outstanding,displayCurrency,rates]);
 const nativeTotals=useMemo(()=>formatCurrencyTotals(groupCurrencyTotals(outstanding,i=>Number(i.amount||0),i=>i.currency||'USD')),[outstanding]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();try{await adminApi('/api/invoices',{method:'POST',body:JSON.stringify({client_id:Number(form.client_id),invoice_no:form.invoice_no.trim(),status:form.status,currency:form.currency,due_date:form.due_date||null,notes:form.notes,items:[{description:form.description,quantity:Number(form.quantity||1),unit_price:Number(form.unit_price||0)}]})});setOpen(false);notify('Invoice created');await load()}catch(e){notify(e instanceof Error?e.message:'Unable to create invoice','error')}};
 const patch=async(id:number,next:string)=>{try{await adminApi(`/api/invoices/${id}`,{method:'PATCH',body:JSON.stringify({status:next})});setRows(v=>v.map(x=>x.id===id?{...x,status:next}:x));notify('Invoice status updated')}catch(e){notify(e instanceof Error?e.message:'Update failed','error')}};
 const remove=async(id:number)=>{if(!isSuper)return;if(!window.confirm('Permanently delete this invoice? This cannot be undone.'))return;try{await adminApi('/api/bulk',{method:'POST',body:JSON.stringify({entity:'invoices',ids:[id],action:'delete'})});notify('Invoice deleted');await load()}catch(e){notify(e instanceof Error?e.message:'Delete failed','error')}};
 return <div className="ix-finance-v18"><PageTop eyebrow="FINANCE" title="Invoices" text="Original record currencies stay intact. Dashboard totals are converted only when a valid live FX rate is available." action={<button className="ix-btn ix-primary" onClick={()=>setOpen(true)}><Plus size={16}/> New invoice</button>}/>
  <div className="ix-finance-kpis"><Kpi label="Invoices" value={loading?'—':rows.length} meta="All records"/><Kpi label="Open" value={loading?'—':outstanding.length} meta="Sent + due"/><Kpi label="Paid" value={loading?'—':rows.filter(i=>i.status==='paid').length} meta="Completed"/><Kpi label={`Displayed total · ${displayCurrency}`} value={loading?'—':displayTotal===null?nativeTotals:formatMoney(displayTotal,displayCurrency)} meta={displayTotal===null?'FX unavailable — showing original currencies':`Converted to ${displayCurrency} using ${rates?.source||'live FX'}`}/></div>
  <div className="ix-finance-toolbar"><label className="ix-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search invoices, clients or status"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{INVOICE_STATUS.map(x=><option value={x} key={x}>{label(x)}</option>)}</select><button className="ix-btn" onClick={()=>void load()} disabled={loading}><RefreshCw size={14}/> Refresh</button></div>
  {error&&<div className="ix-error-bar"><CircleAlert size={15}/><span>{error}</span><button onClick={()=>void load()}>Retry</button></div>}
  <div className="ix-finance-table-wrap"><table className="ix-finance-table"><thead><tr><th>Invoice</th><th>Client</th><th>Status</th><th>Due</th><th>Original amount</th><th>Display amount</th><th/></tr></thead><tbody>{loading?Array.from({length:4}).map((_,i)=><tr className="loading" key={i}>{Array.from({length:7}).map((__,j)=><td key={j}><i/></td>)}</tr>):filtered.map(i=>{const converted=convertMoney(Number(i.amount||0),i.currency||'USD',displayCurrency,rates?.rates);return <tr key={i.id}><td><b>{i.invoice_no}</b><small>{i.paid_at?'Paid':'Invoice'}</small></td><td>{i.client_name||'—'}</td><td><select className="ix-inline-select" value={i.status} onChange={e=>void patch(i.id,e.target.value)}>{INVOICE_STATUS.map(x=><option key={x} value={x}>{label(x)}</option>)}</select></td><td>{i.due_date?prettyDate(i.due_date):'—'}</td><td><strong>{formatMoney(Number(i.amount||0),i.currency||'USD')}</strong><small>{i.currency||'USD'} source value</small></td><td><strong>{converted===null?'—':formatMoney(converted,displayCurrency)}</strong><small>{converted===null?'Rate unavailable':`Converted to ${displayCurrency}`}</small></td><td>{isSuper&&<button className="ix-finance-delete" onClick={()=>void remove(i.id)} title="Delete invoice"><Trash2 size={15}/></button>}</td></tr>})}{!loading&&!filtered.length&&<tr><td colSpan={7}><Empty text="No invoices match these filters."/></td></tr>}</tbody></table></div>
  {open&&<Modal title="New invoice" onClose={()=>setOpen(false)}><form className="ix-form-grid" onSubmit={save}><Field label="Client *"><select required value={form.client_id} onChange={e=>setForm({...form,client_id:e.target.value})}><option value="">Select client</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Invoice number *"><input required value={form.invoice_no} onChange={e=>setForm({...form,invoice_no:e.target.value})}/></Field><Field label="Status"><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{INVOICE_STATUS.map(x=><option key={x} value={x}>{label(x)}</option>)}</select></Field><Field label="Currency"><select value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}>{CURRENCIES.map(c=><option key={c.code} value={c.code}>{c.code} — {c.name}</option>)}</select></Field><Field label="Due date"><input type="date" value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})}/></Field><Field label="Description" wide><input required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><Field label="Quantity"><input type="number" min="0.01" step="0.01" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></Field><Field label="Unit price"><input type="number" min="0" step="0.01" value={form.unit_price} onChange={e=>setForm({...form,unit_price:e.target.value})}/></Field><Field label="Notes" wide><textarea rows={4} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field><div className="ix-modal-actions wide"><button type="button" className="ix-btn" onClick={()=>setOpen(false)}>Cancel</button><button className="ix-btn ix-primary">Create invoice</button></div></form></Modal>}
 </div>
}

export function ReportsPageV18(){
 const displayCurrency=useDisplayCurrency();
 const[data,setData]=useState<Report|null>(null),[invoices,setInvoices]=useState<Invoice[]|null>(null),[rates,setRates]=useState<FxPayload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');const settled=await Promise.allSettled([adminApi<Report>('/api/reports'),adminApi<D1Result<Invoice>>('/api/invoices'),adminApi<FxPayload>('/api/fx')]);if(settled[0].status==='fulfilled')setData(settled[0].value);else setError(settled[0].reason instanceof Error?settled[0].reason.message:'Unable to load reports');setInvoices(settled[1].status==='fulfilled'?(settled[1].value.results||[]):null);if(settled[2].status==='fulfilled')setRates(settled[2].value);setLoading(false)};
 useEffect(()=>{void load()},[]);
 const outstanding=useMemo(()=>invoices?.filter(i=>['sent','due'].includes(i.status))||null,[invoices]);
 const total=useMemo(()=>outstanding?convertedTotal(outstanding,displayCurrency,rates?.rates):null,[outstanding,displayCurrency,rates]);
 const native=useMemo(()=>outstanding?formatCurrencyTotals(groupCurrencyTotals(outstanding,i=>Number(i.amount||0),i=>i.currency||'USD')):'Restricted',[outstanding]);
 const statuses=(title:string,rows:Array<{status:string;count:number}>)=><section className="ix-report-card"><header><span>STATUS MIX</span><h3>{title}</h3></header><div className="ix-report-bars">{rows.map(r=><div key={r.status}><span>{label(r.status)}</span><div><i style={{width:`${Math.min(100,Math.max(8,r.count*12))}%`}}/></div><b>{r.count}</b></div>)}</div></section>;
 return <div className="ix-finance-v18"><PageTop eyebrow="INSIGHTS" title="Reports" text="Operational reporting with currency-safe finance summaries. Mixed currencies are never added together without conversion." action={<button className="ix-btn" onClick={()=>void load()} disabled={loading}><RefreshCw size={15}/> Refresh</button>}/>{error&&<div className="ix-error-bar"><CircleAlert size={15}/><span>{error}</span><button onClick={()=>void load()}>Retry</button></div>}
  <div className="ix-finance-kpis"><Kpi label="Overdue tasks" value={loading?'—':data?.overdueTasks??0} meta="Needs attention"/><Kpi label={`Outstanding · ${displayCurrency}`} value={loading?'—':total===null?native:formatMoney(total,displayCurrency)} meta={total===null?(invoices?'FX unavailable — original currencies':'Invoice access restricted'):`Live conversion to ${displayCurrency}`}/><Kpi label="Recent activity" value={loading?'—':data?.recentActivities?.length??0} meta="Audit events"/><Kpi label="System health" value={error?'Review':'Good'} meta={error?'Some report data unavailable':'Report endpoints responding'}/></div>
  {data&&<><div className="ix-report-grid">{statuses('Task pipeline',data.taskStatus)}{statuses('Content pipeline',data.contentStatus)}{statuses('Clients',data.clientStatus)}{statuses('Projects',data.projectStatus)}</div><section className="ix-report-card ix-report-activity"><header><span>AUDIT TRAIL</span><h3>Recent activity</h3></header><div>{data.recentActivities.map((a:any)=><article key={a.id}><i/><div><b>{label(String(a.action||'activity').replaceAll('.',' '))}</b><small>{a.user_name||'System'} · {a.detail||a.entity_type||''}</small></div><time>{a.created_at?prettyDateTime(a.created_at):''}</time></article>)}{!data.recentActivities.length&&<Empty text="No recent activity."/>}</div></section></>}
 </div>
}

function PageTop({eyebrow,title,text,action}:{eyebrow:string;title:string;text:string;action?:ReactNode}){return <div className="ix-page-top"><div><span>{eyebrow}</span><h2>{title}</h2><p>{text}</p></div>{action&&<div className="ix-page-actions">{action}</div>}</div>}
function Kpi({label:caption,value,meta}:{label:string;value:ReactNode;meta:string}){return <article><small>{caption}</small><b>{value}</b><span>{meta}</span></article>}
function Empty({text}:{text:string}){return <div className="ix-finance-empty"><WalletCards size={25}/><span>{text}</span></div>}
function Field({label:caption,children,wide=false}:{label:string;children:ReactNode;wide?:boolean}){return <label className={`ix-field ${wide?'wide':''}`}><span>{caption}</span>{children}</label>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <div className="ix-modal-backdrop" onMouseDown={onClose}><section className="ix-modal ix-finance-modal" onMouseDown={e=>e.stopPropagation()}><header><div><span>FINANCE</span><h3>{title}</h3></div><button onClick={onClose}>×</button></header>{children}</section></div>}
