import React,{useEffect,useMemo,useRef,useState}from'react';
import{AtSign,Building2,ChevronDown,MessageCircleMore,Search,Send,Smile,X}from'lucide-react';
import{adminApi,type AppUser,type D1Result}from'./admin-api';
import'./admin-chat-v11.css';

type Client={id:number;name:string;company?:string|null};
type Msg={id:number;user_id:number;client_id:number|null;message:string;created_at:string;user_name:string;user_role:string;client_name?:string|null};
type Access={chat:boolean};
const QUICK=['On it','Done','Need review','Waiting on client','Please check'];

export default function AdminChatV11(){
 const[enabled,setEnabled]=useState(false),[open,setOpen]=useState(false),[user,setUser]=useState<AppUser|null>(null),[clients,setClients]=useState<Client[]>([]),[clientId,setClientId]=useState('general'),[messages,setMessages]=useState<Msg[]>([]),[text,setText]=useState(''),[query,setQuery]=useState(''),[sending,setSending]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[unread,setUnread]=useState(0);const endRef=useRef<HTMLDivElement|null>(null),inputRef=useRef<HTMLTextAreaElement|null>(null),lastSeen=useRef(0);
 useEffect(()=>{Promise.all([adminApi<{user:AppUser}>('/api/me'),adminApi<{access:Access}>('/api/access/me'),adminApi<D1Result<Client>>('/api/clients')]).then(([me,a,c])=>{setUser(me.user);setEnabled(!!a.access.chat);setClients(c.results||[])}).catch(()=>setEnabled(false))},[]);
 useEffect(()=>{const h=(e:Event)=>{const id=Number((e as CustomEvent<number>).detail);if(id){if(window.matchMedia('(max-width:760px)').matches){location.assign('/admin/chat');return}setClientId(String(id));setOpen(true);setTimeout(()=>inputRef.current?.focus(),80)}};window.addEventListener('idealab:chat-client',h);return()=>window.removeEventListener('idealab:chat-client',h)},[]);
 useEffect(()=>{if(!enabled)return;const key=(e:KeyboardEvent)=>{const tag=(e.target as HTMLElement)?.tagName?.toLowerCase();if(['input','textarea','select'].includes(tag))return;if((e.key==='c'||e.key==='C')&&!e.ctrlKey&&!e.metaKey&&!e.altKey){e.preventDefault();if(window.matchMedia('(max-width:760px)').matches)location.assign('/admin/chat');else setOpen(v=>!v)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[enabled]);
 const path=useMemo(()=>clientId==='general'?'/api/chat':`/api/chat?client_id=${clientId}`,[clientId]);
 const load=async(silent=false)=>{if(!enabled)return;if(!silent)setLoading(true);try{const r=await adminApi<D1Result<Msg>>(path),next=r.results||[];setMessages(next);const newest=next.at(-1)?.id||0;if(!open&&newest>lastSeen.current&&lastSeen.current>0)setUnread(v=>v+next.filter(m=>m.id>lastSeen.current&&m.user_id!==user?.id).length);if(open){lastSeen.current=newest;setUnread(0)}setError('')}catch(e){if(!silent)setError(e instanceof Error?e.message:'Unable to load chat')}finally{if(!silent)setLoading(false)}};
 useEffect(()=>{if(!enabled)return;void load();const timer=window.setInterval(()=>void load(true),5000);return()=>window.clearInterval(timer)},[enabled,path,open,user?.id]);
 useEffect(()=>{if(open){setUnread(0);lastSeen.current=messages.at(-1)?.id||lastSeen.current;setTimeout(()=>inputRef.current?.focus(),80)}},[open]);
 useEffect(()=>{endRef.current?.scrollIntoView({behavior:'smooth'})},[messages,open]);
 const send=async(message=text.trim())=>{if(!message||sending)return;setSending(true);setError('');try{await adminApi('/api/chat',{method:'POST',body:JSON.stringify({message,client_id:clientId==='general'?null:Number(clientId)})});setText('');await load(true);setTimeout(()=>inputRef.current?.focus(),20)}catch(e){setError(e instanceof Error?e.message:'Unable to send message')}finally{setSending(false)}};
 const filtered=messages.filter(m=>!query.trim()||`${m.user_name} ${m.message}`.toLowerCase().includes(query.toLowerCase()));const current=clientId==='general'?null:clients.find(c=>String(c.id)===clientId);
 if(!enabled)return null;
 const launch=()=>{if(window.matchMedia('(max-width:760px)').matches){location.assign('/admin/chat');return}setOpen(v=>!v)};
 return <><button className="il-chatv11-launch" onClick={launch}><MessageCircleMore size={19}/><span>Chat</span>{unread>0&&<b>{Math.min(unread,99)}</b>}<kbd>C</kbd></button>{open&&<aside className="il-chatv11-panel"><header><div><span className="pulse"/><div><small>COLLABORATION</small><h3>{current?.name||'Team chat'}</h3></div></div><button onClick={()=>setOpen(false)}><X size={17}/></button></header><div className="il-chatv11-context"><label><Building2 size={13}/><select value={clientId} onChange={e=>{setClientId(e.target.value);setQuery('')}}><option value="general">General team chat</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}{c.company?` — ${c.company}`:''}</option>)}</select><ChevronDown size={12}/></label><button title="Search messages" onClick={()=>{const el=document.querySelector<HTMLInputElement>('.il-chatv11-search input');el?.focus()}}><Search size={14}/></button></div><label className="il-chatv11-search"><Search size={13}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search this conversation…"/></label><div className="il-chatv11-quick">{QUICK.map(q=><button key={q} onClick={()=>void send(q)}>{q}</button>)}</div><div className="il-chatv11-messages">{loading&&!messages.length?<div className="il-chatv11-empty">Loading conversation…</div>:filtered.map((m,i)=>{const mine=m.user_id===user?.id,prev=filtered[i-1],newGroup=!prev||prev.user_id!==m.user_id||new Date(m.created_at).getTime()-new Date(prev.created_at).getTime()>10*60*1000;return <div className={`il-chatv11-msg ${mine?'mine':''}`} key={m.id}>{newGroup&&<div className="il-chatv11-author"><span className="avatar">{m.user_name.slice(0,1).toUpperCase()}</span><b>{mine?'You':m.user_name}</b><small>{m.user_role.replaceAll('_',' ')}</small></div>}<div className="bubble"><p>{m.message}</p><time>{new Date(m.created_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</time></div></div>})}{!filtered.length&&!loading&&<div className="il-chatv11-empty"><MessageCircleMore size={24}/><b>{query?'No matching messages':'Start the conversation'}</b><span>{query?'Try another search.':'Use a quick reply or type a message below.'}</span></div>}<div ref={endRef}/></div>{error&&<div className="il-chatv11-error">{error}</div>}<div className="il-chatv11-compose"><div className="il-chatv11-composebar"><button title="Mention" onClick={()=>setText(v=>v+'@')}><AtSign size={15}/></button><textarea ref={inputRef} rows={1} value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send()}}} placeholder={current?`Message about ${current.name}…`:'Message the team…'}/><button title="Add emoji" onClick={()=>setText(v=>v+' 🙂')}><Smile size={15}/></button><button className="send" disabled={!text.trim()||sending} onClick={()=>void send()}><Send size={15}/></button></div><small>Enter to send · Shift + Enter for new line</small></div></aside>}</>;
}
