import React,{useEffect,useMemo,useRef,useState}from'react';
import{ArrowLeft,AtSign,CheckCheck,ChevronDown,CirclePlus,Hash,MessageCircleMore,MoreVertical,Reply,Search,Send,Settings2,Trash2,Users,X}from'lucide-react';
import{adminApi}from'./admin-api';
import{useEnterprisePortal}from'./admin-enterprise-v17';
import'./admin-enterprise-chat-v19.css';

type Person={id:number;name:string;email?:string;role:string;avatar_url:string|null;profile_icon:string|null;profile_color:string|null};
type Conv={key:string;type:'general'|'client'|'dm'|'space';target_id:number|null;title:string;subtitle:string;avatar:string;avatar_url?:string|null;profile_icon?:string|null;profile_color?:string|null;last_message:string;last_at:string|null;last_sender:string|null;unread:number;member_count?:number;created_by?:number};
type Msg={id:number;user_id:number;client_id:number|null;recipient_user_id:number|null;space_id:number|null;reply_to_id:number|null;message:string;created_at:string;user_name:string;user_role:string;avatar_url:string|null;profile_icon:string|null;profile_color:string|null;reply_message?:string|null;reply_user_id?:number|null;reply_user_name?:string|null};
type Bootstrap={results:Conv[];total_unread:number;people:Person[];me:Person;capabilities:{spaces:boolean;mentions:boolean;replies:boolean;profiles:boolean}};
const draftKey=(key:string)=>`ix-chat-v19-draft:${key}`;
const PALETTE=['#6d5dfc','#0ea5e9','#06b6d4','#10b981','#f59e0b','#ec4899','#ef4444','#8b5cf6'];
const ICONS=['💬','🚀','📣','🧠','🎨','💼','📈','⚡','🛠️','✅','🔥','🌐'];

function Avatar({name,url,icon,color,size='md'}:{name:string;url?:string|null;icon?:string|null;color?:string|null;size?:'sm'|'md'|'lg'}){return <span className={`ix19-avatar ${size}`} style={{background:color||'#6d5dfc'}}>{url?<img src={url} alt="" loading="lazy" referrerPolicy="no-referrer"/>:icon||name.slice(0,1).toUpperCase()}</span>}
function when(value:string|null){if(!value)return'';const d=new Date(value),now=new Date();if(d.toDateString()===now.toDateString())return d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});return d.toLocaleDateString([],{month:'short',day:'numeric'})}

export default function EnterpriseChatV19(){
 const{user,isSuper,notify}=useEnterprisePortal();
 const[boot,setBoot]=useState<Bootstrap|null>(null),[channel,setChannel]=useState('general'),[messages,setMessages]=useState<Msg[]>([]),[text,setText]=useState(''),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[sending,setSending]=useState(false),[mobileOpen,setMobileOpen]=useState(false),[createSpace,setCreateSpace]=useState(false),[manageSpace,setManageSpace]=useState(false),[profileOpen,setProfileOpen]=useState(false),[reply,setReply]=useState<Msg|null>(null),[mentionOpen,setMentionOpen]=useState(false),[mentionQuery,setMentionQuery]=useState(''),[mentionIds,setMentionIds]=useState<number[]>([]),[error,setError]=useState('');
 const boxRef=useRef<HTMLDivElement|null>(null),inputRef=useRef<HTMLTextAreaElement|null>(null),lastId=useRef(0),polling=useRef(false),first=useRef(true);
 const convs=boot?.results||[],people=boot?.people||[],current=useMemo(()=>convs.find(c=>c.key===channel)||convs[0],[convs,channel]);
 const filtered=useMemo(()=>convs.filter(c=>!query.trim()||`${c.title} ${c.subtitle} ${c.last_message}`.toLowerCase().includes(query.toLowerCase())),[convs,query]);
 const groups={spaces:filtered.filter(c=>c.type==='space'||c.type==='general'),clients:filtered.filter(c=>c.type==='client'),direct:filtered.filter(c=>c.type==='dm')};
 const nearBottom=()=>{const el=boxRef.current;return !el||el.scrollHeight-el.scrollTop-el.clientHeight<140};
 const scrollBottom=(smooth=false)=>requestAnimationFrame(()=>{const el=boxRef.current;if(el)el.scrollTo({top:el.scrollHeight,behavior:smooth?'smooth':'auto'})});
 const loadBootstrap=async(silent=false)=>{try{const b=await adminApi<Bootstrap>('/api/chat-v3/bootstrap');setBoot(b);if(!b.results.some(c=>c.key===channel)&&b.results.length)setChannel(b.results[0].key);if(!silent)setError('')}catch(e){if(!silent)setError(e instanceof Error?e.message:'Unable to load chat')}finally{if(!silent)setLoading(false)}};
 const loadMessages=async(initial=false)=>{if(!channel||polling.current||document.hidden)return;polling.current=true;const after=initial?0:lastId.current;const stick=initial||nearBottom();try{const r=await adminApi<{results:Msg[]}>(`/api/chat-v3/messages?channel=${encodeURIComponent(channel)}&after_id=${after}&limit=${initial?70:50}`);const next=r.results||[];if(initial){setMessages(next);lastId.current=next.at(-1)?.id||0}else if(next.length){setMessages(prev=>{const ids=new Set(prev.map(x=>x.id));return[...prev,...next.filter(x=>!ids.has(x.id))]});lastId.current=Math.max(lastId.current,next.at(-1)?.id||0)}if(stick&&next.length)scrollBottom(!first.current&&!initial);if(next.length)void adminApi('/api/chat-v3/read',{method:'POST',body:JSON.stringify({channel,last_message_id:lastId.current})}).catch(()=>{});setError('')}catch(e){if(initial)setError(e instanceof Error?e.message:'Unable to load messages')}finally{polling.current=false;first.current=false}}
 useEffect(()=>{void loadBootstrap();const onFocus=()=>{void loadBootstrap(true);void loadMessages(false)};window.addEventListener('focus',onFocus);return()=>window.removeEventListener('focus',onFocus)},[]);
 useEffect(()=>{first.current=true;lastId.current=0;setMessages([]);setReply(null);setMentionIds([]);setText(localStorage.getItem(draftKey(channel))||'');void loadMessages(true);const timer=window.setInterval(()=>void loadMessages(false),5000);return()=>window.clearInterval(timer)},[channel]);
 useEffect(()=>{const t=window.setTimeout(()=>{if(text)localStorage.setItem(draftKey(channel),text);else localStorage.removeItem(draftKey(channel))},250);return()=>window.clearTimeout(t)},[text,channel]);
 useEffect(()=>{if(!boot)return;const t=window.setInterval(()=>{if(!document.hidden)void loadBootstrap(true)},20000);return()=>window.clearInterval(t)},[boot]);
 const open=(key:string)=>{setChannel(key);setMobileOpen(true);window.setTimeout(()=>inputRef.current?.focus(),60)};
 const send=async()=>{const value=text.trim();if(!value||sending)return;setSending(true);const optimisticId=-Date.now(),mine:Msg={id:optimisticId,user_id:user.id,client_id:null,recipient_user_id:null,space_id:current?.type==='space'?current.target_id:null,reply_to_id:reply?.id||null,message:value,created_at:new Date().toISOString(),user_name:user.name,user_role:user.role,avatar_url:boot?.me.avatar_url||null,profile_icon:boot?.me.profile_icon||null,profile_color:boot?.me.profile_color||null,reply_message:reply?.message||null,reply_user_name:reply?.user_name||null};setMessages(prev=>[...prev,mine]);setText('');setReply(null);scrollBottom(true);try{const r=await adminApi<{message:Msg}>('/api/chat-v3/messages',{method:'POST',body:JSON.stringify({channel,message:value,reply_to_id:mine.reply_to_id,mention_user_ids:mentionIds})});setMessages(prev=>prev.map(m=>m.id===optimisticId?r.message:m));lastId.current=Math.max(lastId.current,r.message.id);setMentionIds([]);localStorage.removeItem(draftKey(channel));void loadBootstrap(true)}catch(e){setMessages(prev=>prev.filter(m=>m.id!==optimisticId));setText(value);notify(e instanceof Error?e.message:'Message failed','error')}finally{setSending(false)}};
 const remove=async(id:number)=>{if(!isSuper||id<0)return;if(!confirm('Permanently delete this message?'))return;try{await adminApi(`/api/chat-v2/messages/${id}`,{method:'DELETE',body:JSON.stringify({channel})});setMessages(v=>v.filter(m=>m.id!==id));notify('Message deleted');void loadBootstrap(true)}catch(e){notify(e instanceof Error?e.message:'Delete failed','error')}};
 const mentionCandidates=people.filter(p=>p.id!==user.id&&(!mentionQuery||`${p.name} ${p.role}`.toLowerCase().includes(mentionQuery.toLowerCase()))).slice(0,8);
 const addMention=(p:Person)=>{setMentionIds(v=>[...new Set([...v,p.id])]);const at=`@${p.name}`;setText(v=>v.replace(/@[^\s@]*$/,at+' '));setMentionOpen(false);setMentionQuery('');inputRef.current?.focus()};
 const onText=(value:string)=>{setText(value);const m=/(?:^|\s)@([^\s@]*)$/.exec(value);if(m){setMentionOpen(true);setMentionQuery(m[1]||'')}else setMentionOpen(false)};
 return <div className="ix19-chat-shell">
  <aside className={`ix19-chat-list ${mobileOpen?'mobile-hidden':''}`}><header><div><span>COLLABORATION</span><h2>Messages</h2></div><button className="ix19-new-space" onClick={()=>setCreateSpace(true)} title="New team space"><CirclePlus size={18}/></button></header><label className="ix19-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search chats"/></label><div className="ix19-list-scroll">{loading?<div className="ix19-empty">Loading…</div>:<><ChatGroup title="Team spaces" rows={groups.spaces} channel={channel} open={open}/><ChatGroup title="Clients" rows={groups.clients} channel={channel} open={open}/><ChatGroup title="Direct messages" rows={groups.direct} channel={channel} open={open}/></>}</div></aside>
  <main className={`ix19-thread ${mobileOpen?'mobile-show':''}`}>{current?<><header className="ix19-thread-head"><button className="ix19-back" onClick={()=>setMobileOpen(false)}><ArrowLeft size={18}/></button><Avatar name={current.title} url={current.avatar_url} icon={current.profile_icon||current.avatar} color={current.profile_color}/><div className="ix19-thread-title"><b>{current.title}</b><span>{current.type==='space'&&current.member_count?`${current.member_count} members · `:''}{current.subtitle}</span></div><div className="ix19-head-actions">{current.type==='space'&&<button onClick={()=>setManageSpace(true)} title="Manage space"><Users size={17}/></button>}<button onClick={()=>setProfileOpen(true)} title="Profile"><Settings2 size={17}/></button><button title="More"><MoreVertical size={18}/></button></div></header>
   <div className="ix19-messages" ref={boxRef}>{messages.map((m,i)=>{const mine=m.user_id===user.id,prev=messages[i-1],group=!prev||prev.user_id!==m.user_id||new Date(m.created_at).getTime()-new Date(prev.created_at).getTime()>7*60*1000;return <div key={m.id} className={`ix19-msg ${mine?'mine':''} ${m.id<0?'pending':''}`}>{!mine&&group&&<Avatar size="sm" name={m.user_name} url={m.avatar_url} icon={m.profile_icon} color={m.profile_color}/>}<div className="ix19-msg-stack">{!mine&&group&&<div className="ix19-author"><b>{m.user_name}</b><span>{m.user_role.replaceAll('_',' ')}</span></div>}<div className="ix19-bubble">{m.reply_message&&<div className="ix19-reply-preview"><b>{m.reply_user_name||'Reply'}</b><span>{m.reply_message}</span></div>}<p>{renderMessage(m.message,people)}</p><footer><time>{new Date(m.created_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</time>{mine&&<CheckCheck size={12}/>}<button onClick={()=>setReply(m)} title="Reply"><Reply size={12}/></button>{isSuper&&m.id>0&&<button onClick={()=>void remove(m.id)} title="Delete"><Trash2 size={12}/></button>}</footer></div></div></div>})}{!messages.length&&!loading&&<div className="ix19-thread-empty"><MessageCircleMore size={34}/><b>Start the conversation</b><span>Use @ to mention teammates, or reply to any message.</span></div>}</div>
   {error&&<div className="ix19-error"><span>{error}</span><button onClick={()=>void loadMessages(true)}>Retry</button></div>}
   <footer className="ix19-composer">{reply&&<div className="ix19-replying"><Reply size={14}/><div><b>Replying to {reply.user_id===user.id?'yourself':reply.user_name}</b><span>{reply.message}</span></div><button onClick={()=>setReply(null)}><X size={15}/></button></div>}{mentionOpen&&<div className="ix19-mentions">{mentionCandidates.map(p=><button key={p.id} onMouseDown={e=>{e.preventDefault();addMention(p)}}><Avatar size="sm" name={p.name} url={p.avatar_url} icon={p.profile_icon} color={p.profile_color}/><span><b>{p.name}</b><small>{p.role.replaceAll('_',' ')}</small></span></button>)}{!mentionCandidates.length&&<div>No matching teammate</div>}</div>}<div className="ix19-compose-box"><button onClick={()=>{setMentionOpen(true);setMentionQuery('')}} title="Mention teammate"><AtSign size={18}/></button><textarea ref={inputRef} rows={1} value={text} onChange={e=>onText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send()}if(e.key==='Escape'){setMentionOpen(false);setReply(null)}}} placeholder={`Message ${current.title}`}/><button className="ix19-send" disabled={!text.trim()||sending} onClick={()=>void send()}><Send size={18}/></button></div><small>Enter to send · Shift + Enter for a new line · @ to mention</small></footer>
  </>:<div className="ix19-thread-empty"><MessageCircleMore size={34}/><b>Select a conversation</b></div>}</main>
  {createSpace&&<SpaceModal people={people} close={()=>setCreateSpace(false)} saved={async id=>{setCreateSpace(false);await loadBootstrap();open(`space:${id}`);notify('Team space created')}}/>}
  {manageSpace&&current?.type==='space'&&<SpaceModal people={people} existing={current} close={()=>setManageSpace(false)} saved={async()=>{setManageSpace(false);await loadBootstrap();notify('Team space updated')}}/>}
  {profileOpen&&<ProfileModal me={boot?.me||null} close={()=>setProfileOpen(false)} saved={async()=>{setProfileOpen(false);await loadBootstrap();notify('Profile updated')}}/>}
 </div>
}

function ChatGroup({title,rows,channel,open}:{title:string;rows:Conv[];channel:string;open:(key:string)=>void}){if(!rows.length)return null;return <section className="ix19-group"><h3>{title}<span>{rows.length}</span></h3>{rows.map(c=><button key={c.key} className={c.key===channel?'active':''} onClick={()=>open(c.key)}><Avatar name={c.title} url={c.avatar_url} icon={c.profile_icon||c.avatar} color={c.profile_color}/><div><b>{c.title}</b><p>{c.last_message?(c.last_sender?`${c.last_sender}: ${c.last_message}`:c.last_message):c.subtitle}</p></div><aside><time>{when(c.last_at)}</time>{c.unread>0&&<span>{Math.min(99,c.unread)}</span>}</aside></button>)}</section>}
function renderMessage(text:string,people:Person[]){const names=[...people].sort((a,b)=>b.name.length-a.name.length);let nodes:React.ReactNode[]=[text];for(const p of names){nodes=nodes.flatMap((n:any,i)=>typeof n!=='string'?[n]:n.split(`@${p.name}`).flatMap((part:string,j,arr:string[])=>j<arr.length-1?[part,<mark key={`${p.id}-${i}-${j}`}>@{p.name}</mark>]:[part]))}return nodes}

function SpaceModal({people,existing,close,saved}:{people:Person[];existing?:Conv;close:()=>void;saved:(id:number)=>Promise<void>}){const[form,setForm]=useState({name:existing?.title||'',description:existing?.subtitle||'',icon:existing?.profile_icon||'💬',color:existing?.profile_color||'#6d5dfc',member_ids:people.map(p=>p.id)}),[saving,setSaving]=useState(false),[error,setError]=useState('');const go=async()=>{if(!form.name.trim())return;setSaving(true);setError('');try{if(existing?.target_id){await adminApi(`/api/chat-v3/spaces/${existing.target_id}`,{method:'PATCH',body:JSON.stringify(form)});await saved(existing.target_id)}else{const r=await adminApi<{id:number}>('/api/chat-v3/spaces',{method:'POST',body:JSON.stringify(form)});await saved(r.id)}}catch(e){setError(e instanceof Error?e.message:'Unable to save space')}finally{setSaving(false)}};return <div className="ix19-modal-backdrop" onMouseDown={close}><section className="ix19-modal" onMouseDown={e=>e.stopPropagation()}><header><div><span>TEAM SPACE</span><h3>{existing?'Edit team space':'Create team space'}</h3></div><button onClick={close}><X size={18}/></button></header><div className="ix19-modal-body"><label><span>Name</span><input autoFocus value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="e.g. Marketing"/></label><label><span>Description</span><input value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="What this space is for"/></label><div className="ix19-picker"><span>Icon</span><div>{ICONS.map(x=><button className={form.icon===x?'active':''} onClick={()=>setForm({...form,icon:x})} key={x}>{x}</button>)}</div></div><div className="ix19-picker"><span>Color</span><div>{PALETTE.map(x=><button className={form.color===x?'active':''} style={{background:x}} onClick={()=>setForm({...form,color:x})} key={x}/>)}</div></div><div className="ix19-members"><span>Members</span><div>{people.map(p=><label key={p.id}><input type="checkbox" checked={form.member_ids.includes(p.id)} onChange={e=>setForm({...form,member_ids:e.target.checked?[...new Set([...form.member_ids,p.id])]:form.member_ids.filter(x=>x!==p.id)})}/><Avatar size="sm" name={p.name} url={p.avatar_url} icon={p.profile_icon} color={p.profile_color}/><span><b>{p.name}</b><small>{p.role.replaceAll('_',' ')}</small></span></label>)}</div></div>{error&&<div className="ix19-modal-error">{error}</div>}</div><footer><button onClick={close}>Cancel</button><button className="primary" disabled={saving||!form.name.trim()} onClick={()=>void go()}>{saving?'Saving…':existing?'Save changes':'Create space'}</button></footer></section></div>}

function ProfileModal({me,close,saved}:{me:Person|null;close:()=>void;saved:()=>Promise<void>}){const[form,setForm]=useState({name:me?.name||'',avatar_url:me?.avatar_url||'',profile_icon:me?.profile_icon||'👤',profile_color:me?.profile_color||'#6d5dfc'}),[saving,setSaving]=useState(false),[error,setError]=useState('');const go=async()=>{setSaving(true);setError('');try{await adminApi('/api/profile/me',{method:'PATCH',body:JSON.stringify(form)});await saved()}catch(e){setError(e instanceof Error?e.message:'Unable to update profile')}finally{setSaving(false)}};return <div className="ix19-modal-backdrop" onMouseDown={close}><section className="ix19-modal profile" onMouseDown={e=>e.stopPropagation()}><header><div><span>YOUR PROFILE</span><h3>Chat identity</h3></div><button onClick={close}><X size={18}/></button></header><div className="ix19-profile-preview"><Avatar size="lg" name={form.name||'User'} url={form.avatar_url} icon={form.profile_icon} color={form.profile_color}/><div><b>{form.name||'Your name'}</b><span>{me?.role.replaceAll('_',' ')}</span></div></div><div className="ix19-modal-body"><label><span>Display name</span><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label><span>Profile photo URL</span><input value={form.avatar_url} onChange={e=>setForm({...form,avatar_url:e.target.value})} placeholder="https://…"/><small>Use a secure HTTPS image URL, or choose an icon below.</small></label><div className="ix19-picker"><span>Icon</span><div>{['👤','🧑‍💼','👩‍💻','👨‍💻','🧠','🚀','🎨','📈'].map(x=><button className={form.profile_icon===x?'active':''} onClick={()=>setForm({...form,profile_icon:x})} key={x}>{x}</button>)}</div></div><div className="ix19-picker"><span>Color</span><div>{PALETTE.map(x=><button className={form.profile_color===x?'active':''} style={{background:x}} onClick={()=>setForm({...form,profile_color:x})} key={x}/>)}</div></div>{error&&<div className="ix19-modal-error">{error}</div>}</div><footer><button onClick={close}>Cancel</button><button className="primary" disabled={saving||!form.name.trim()} onClick={()=>void go()}>{saving?'Saving…':'Save profile'}</button></footer></section></div>}
