import React,{useEffect,useMemo,useState}from'react';
import{BadgeCheck,Check,Copy,Eye,EyeOff,Fingerprint,KeyRound,Mail,Plus,Search,ShieldCheck,Sparkles,Trash2,UserCheck,UsersRound,X}from'lucide-react';
import{adminApi,type Role}from'./admin-api';
import{useEnterprisePortal,type AccessMap,type ModuleKey}from'./admin-enterprise-v17';

type AccessUser={id:number;name:string;email:string;role:Role;active:number;last_login_at?:string|null;access:AccessMap;client_ids:number[]};
type Client={id:number;name:string;company?:string|null};
const ASSIGNABLE:Exclude<Role,'super_admin'>[]=['admin','sales','project_manager','finance','content'];
const MODULES:ModuleKey[]=['leads','clients','projects','tasks','content','invoices','chat','reports'];
const labels:Record<ModuleKey,string>={leads:'Leads',clients:'Clients',projects:'Projects',tasks:'Tasks',invoices:'Invoices',content:'Content',reports:'Reports',settings:'Settings',chat:'Chat'};
const roleHint:Record<Exclude<Role,'super_admin'>,string>={admin:'Broad operations access',sales:'Leads and client relationships',project_manager:'Projects, tasks and content delivery',finance:'Invoices and financial reporting',content:'Client content planning'};
const roleLabel=(role:Role)=>role.replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase());
function password(){const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%';const bytes=crypto.getRandomValues(new Uint8Array(14));return Array.from(bytes,b=>alphabet[b%alphabet.length]).join('')}
function initials(name:string){return name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'U'}

export default function EnterpriseTeamV18(){
 const{notify,user}=useEnterprisePortal();
 const[rows,setRows]=useState<AccessUser[]>([]),[clients,setClients]=useState<Client[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[create,setCreate]=useState(false),[edit,setEdit]=useState<AccessUser|null>(null),[reset,setReset]=useState<AccessUser|null>(null),[remove,setRemove]=useState<AccessUser|null>(null),[error,setError]=useState('');
 const load=async()=>{setLoading(true);try{const[u,c]=await Promise.all([adminApi<{results:AccessUser[]}>('/api/access/users'),adminApi<{results:Client[]}>('/api/clients')]);setRows(u.results||[]);setClients(c.results||[]);setError('')}catch(e){setError(e instanceof Error?e.message:'Unable to load team')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>rows.filter(r=>`${r.name} ${r.email} ${r.role}`.toLowerCase().includes(query.toLowerCase())),[rows,query]);
 const active=rows.filter(r=>r.active).length,restricted=rows.filter(r=>!r.access?.all_clients&&r.role!=='super_admin').length;
 const toggle=async(target:AccessUser)=>{if(target.id===user.id||target.role==='super_admin')return;try{await adminApi(`/api/users/${target.id}`,{method:'PATCH',body:JSON.stringify({active:!target.active})});notify(target.active?'Account deactivated':'Account activated');await load()}catch(e){notify(e instanceof Error?e.message:'Update failed','error')}};
 const deleteMember=async(target:AccessUser)=>{try{await adminApi(`/api/users/${target.id}`,{method:'DELETE',body:JSON.stringify({confirm:true})});setRemove(null);notify(`${target.name} was deleted`);await load()}catch(e){notify(e instanceof Error?e.message:'Delete failed','error')}};
 return <div className="ix-v18-team">
  <div className="ix-page-top ix-v18-team-head"><div><span>IDENTITY & ACCESS</span><h2>Team control</h2><p>One place for staff identities, client scope and workspace permissions. Destructive actions are restricted to Super Admin.</p></div><div className="ix-page-actions"><button className="ix-btn ix-primary" onClick={()=>setCreate(true)}><Plus size={16}/> Add team member</button></div></div>
  <div className="ix-team-summary ix-v18-summary">
   <article><span className="ix-summary-icon violet"><UserCheck size={18}/></span><div><b>{active}</b><span>Active accounts</span></div></article>
   <article><span className="ix-summary-icon cyan"><Fingerprint size={18}/></span><div><b>{rows.length}</b><span>Managed identities</span></div></article>
   <article><span className="ix-summary-icon pink"><ShieldCheck size={18}/></span><div><b>{restricted}</b><span>Scoped accounts</span></div></article>
  </div>
  <div className="ix-v18-team-toolbar"><label className="ix-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by name, email or role"/></label><div className="ix-security-pill"><BadgeCheck size={14}/><span>Super Admin protected</span></div></div>
  {error&&<div className="ix-error-bar"><span>{error}</span><button onClick={()=>void load()}>Retry</button></div>}
  <div className="ix-team-grid ix-v18-team-grid">{loading?Array.from({length:4}).map((_,i)=><article key={i} className="ix-team-card ix-card-skeleton"><i/><i/><i/></article>):filtered.map(member=>{
   const moduleCount=member.role==='super_admin'?MODULES.length:MODULES.filter(m=>member.access?.[m]).length;
   return <article className={`ix-team-card ix-v18-member ${member.active?'is-active':'is-inactive'}`} key={member.id}>
    <div className="ix-v18-member-top"><div className="ix-member-avatar">{initials(member.name)}<i/></div><div className="ix-v18-member-identity"><div><b>{member.name}</b>{member.role==='super_admin'&&<span className="ix-owner-badge"><ShieldCheck size={11}/> Owner</span>}</div><small><Mail size={11}/>{member.email}</small></div><span className={`ix-account-state ${member.active?'active':'inactive'}`}>{member.active?'Active':'Inactive'}</span></div>
    <div className="ix-v18-member-stats"><div><small>Role</small><b>{roleLabel(member.role)}</b></div><div><small>Modules</small><b>{moduleCount} / {MODULES.length}</b></div><div><small>Clients</small><b>{member.access?.all_clients?'All':member.client_ids?.length||0}</b></div><div><small>Last login</small><b>{member.last_login_at?new Date(member.last_login_at).toLocaleDateString(undefined,{month:'short',day:'numeric'}):'Never'}</b></div></div>
    <div className="ix-v18-scope-line"><span>Access profile</span><div>{member.role==='super_admin'?<><i className="violet"/>Full system control</>:member.access?.all_clients?<><i className="cyan"/>All permitted clients</>:<><i className="pink"/>Restricted client scope</>}</div></div>
    <div className="ix-team-actions ix-v18-member-actions">{member.role!=='super_admin'&&<button className="ix-btn" onClick={()=>setEdit(member)}>Manage access</button>}{member.role!=='super_admin'&&<button className="ix-btn" onClick={()=>setReset(member)}><KeyRound size={14}/> Password</button>}{member.role!=='super_admin'&&member.id!==user.id&&<button className={`ix-btn ${member.active?'ix-danger-soft':''}`} onClick={()=>void toggle(member)}>{member.active?'Deactivate':'Activate'}</button>}{member.role!=='super_admin'&&member.id!==user.id&&<button className="ix-delete-member" onClick={()=>setRemove(member)} title="Delete team member"><Trash2 size={15}/></button>}</div>
   </article>})}{!loading&&!filtered.length&&<div className="ix-team-empty"><UsersRound size={30}/><b>No matching team members</b><span>Try another name, email or role.</span></div>}</div>
  {create&&<CreateModal close={()=>setCreate(false)} after={async created=>{setCreate(false);await load();const next=(await adminApi<{results:AccessUser[]}>('/api/access/users')).results.find(x=>x.id===created);if(next)setEdit(next)}}/>}
  {edit&&<AccessModal member={edit} clients={clients} close={()=>setEdit(null)} saved={async()=>{setEdit(null);notify('Access updated');await load()}}/>}
  {reset&&<ResetModal member={reset} close={()=>setReset(null)} saved={async()=>{setReset(null);notify('Password reset and old sessions closed');await load()}}/>}
  {remove&&<DeleteModal member={remove} close={()=>setRemove(null)} confirm={()=>void deleteMember(remove)}/>} 
 </div>
}

function CreateModal({close,after}:{close:()=>void;after:(id:number)=>Promise<void>}){const{notify}=useEnterprisePortal();const[form,setForm]=useState({name:'',email:'',role:'sales' as Exclude<Role,'super_admin'>,password:''}),[show,setShow]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');const valid=form.name.trim().length>=2&&/^\S+@\S+\.\S+$/.test(form.email)&&form.password.length>=8;const generate=()=>{setForm(v=>({...v,password:password()}));setShow(true)};const copy=async()=>{try{await navigator.clipboard.writeText(form.password);notify('Password copied')}catch{notify('Copy was blocked. Select the password manually.','error')}};const save=async(e:React.FormEvent)=>{e.preventDefault();if(!valid)return;setSaving(true);setError('');try{const r=await adminApi<{id:number}>('/api/users',{method:'POST',body:JSON.stringify({...form,email:form.email.trim().toLowerCase(),name:form.name.trim()})});notify('Team account created');await after(r.id)}catch(e){setError(e instanceof Error?e.message:'Unable to create account')}finally{setSaving(false)}};return <Modal eyebrow="TEAM CONTROL" title="Create a team identity" subtitle="Start with the login. You will set client and module access immediately after creation." close={close}><div className="ix-v18-stepper"><span className="active"><i>1</i> Identity</span><em/><span><i>2</i> Access</span><em/><span><i>3</i> Ready</span></div><form className="ix-form-grid ix-v18-form" onSubmit={save}><Field label="Full name *"><input autoFocus placeholder="e.g. Ayesha Khan" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Work email *"><input type="email" placeholder="name@company.com" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="Role"><select value={form.role} onChange={e=>setForm({...form,role:e.target.value as Exclude<Role,'super_admin'>})}>{ASSIGNABLE.map(x=><option key={x} value={x}>{roleLabel(x)}</option>)}</select><small>{roleHint[form.role]}</small></Field><Field label="Temporary password *"><div className="ix-password-field"><input type={show?'text':'password'} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button type="button" onClick={()=>setShow(v=>!v)}>{show?<EyeOff size={15}/>:<Eye size={15}/>}</button></div><div className="ix-inline-tools"><button type="button" onClick={generate}><Sparkles size={13}/> Generate secure</button><button type="button" disabled={!form.password} onClick={()=>void copy()}><Copy size={13}/> Copy</button></div></Field>{error&&<div className="ix-form-error wide">{error}</div>}<Actions close={close} submit={saving?'Creating…':'Create & continue'} disabled={!valid||saving}/></form></Modal>}

function AccessModal({member,clients,close,saved}:{member:AccessUser;clients:Client[];close:()=>void;saved:()=>Promise<void>}){const[access,setAccess]=useState({...member.access}),[selected,setSelected]=useState<number[]>(member.client_ids||[]),[query,setQuery]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');const filtered=useMemo(()=>clients.filter(c=>`${c.name} ${c.company||''}`.toLowerCase().includes(query.toLowerCase())),[clients,query]);const save=async()=>{setSaving(true);setError('');try{await adminApi(`/api/access/users/${member.id}`,{method:'PATCH',body:JSON.stringify({access,all_clients:access.all_clients,client_ids:access.all_clients?[]:selected})});await saved()}catch(e){setError(e instanceof Error?e.message:'Unable to save access')}finally{setSaving(false)}};return <Modal eyebrow="ACCESS PROFILE" title={member.name} subtitle={`${member.email} · ${roleLabel(member.role)}`} close={close} wide><div className="ix-access-layout ix-v18-access"><section><div className="ix-access-section-head"><span>Workspace modules</span><small>{MODULES.filter(m=>access[m]).length} enabled</small></div><div className="ix-toggle-list">{MODULES.map(m=><label key={m}><span><b>{labels[m]}</b><small>{moduleHelp(m)}</small></span><input type="checkbox" checked={!!access[m]} onChange={e=>setAccess(v=>({...v,[m]:e.target.checked}))}/></label>)}</div></section><section><div className="ix-access-section-head"><span>Client visibility</span><small>{access.all_clients?'Full portfolio':`${selected.length} selected`}</small></div><label className="ix-all-clients"><span><b>All clients</b><small>Can work across the full permitted portfolio</small></span><input type="checkbox" checked={!!access.all_clients} onChange={e=>setAccess(v=>({...v,all_clients:e.target.checked}))}/></label>{!access.all_clients&&<><div className="ix-access-tools"><label><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search clients"/></label><button onClick={()=>setSelected(clients.map(c=>c.id))}>Select all</button><button onClick={()=>setSelected([])}>Clear</button></div><div className="ix-client-picks">{filtered.map(c=><label key={c.id}><input type="checkbox" checked={selected.includes(c.id)} onChange={e=>setSelected(v=>e.target.checked?[...new Set([...v,c.id])]:v.filter(x=>x!==c.id))}/><span><b>{c.name}</b><small>{c.company||'Client account'}</small></span></label>)}</div></>}</section></div>{error&&<div className="ix-form-error">{error}</div>}<div className="ix-modal-actions"><button className="ix-btn" onClick={close}>Cancel</button><button className="ix-btn ix-primary" disabled={saving||(!access.all_clients&&!selected.length)} onClick={()=>void save()}>{saving?'Saving…':<><Check size={15}/> Save access</>}</button></div></Modal>}

function ResetModal({member,close,saved}:{member:AccessUser;close:()=>void;saved:()=>Promise<void>}){const{notify}=useEnterprisePortal();const[value,setValue]=useState(''),[show,setShow]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');const generate=()=>{setValue(password());setShow(true)};const save=async()=>{if(value.length<8)return;setSaving(true);setError('');try{await adminApi(`/api/users/${member.id}`,{method:'PATCH',body:JSON.stringify({password:value})});await saved()}catch(e){setError(e instanceof Error?e.message:'Unable to reset password')}finally{setSaving(false)}};return <Modal eyebrow="SECURITY" title="Reset password" subtitle={`${member.name} · Existing sessions will be closed after reset.`} close={close}><div className="ix-reset-password ix-v18-reset"><div className="ix-password-field"><input autoFocus type={show?'text':'password'} value={value} onChange={e=>setValue(e.target.value)} placeholder="At least 8 characters"/><button onClick={()=>setShow(v=>!v)}>{show?<EyeOff size={15}/>:<Eye size={15}/>}</button></div><div className="ix-inline-tools"><button onClick={generate}><Sparkles size={13}/> Generate secure</button><button disabled={!value} onClick={()=>navigator.clipboard.writeText(value).then(()=>notify('Password copied')).catch(()=>notify('Copy failed','error'))}><Copy size={13}/> Copy</button></div>{error&&<div className="ix-form-error">{error}</div>}</div><div className="ix-modal-actions"><button className="ix-btn" onClick={close}>Cancel</button><button className="ix-btn ix-primary" disabled={value.length<8||saving} onClick={()=>void save()}>{saving?'Resetting…':'Reset password'}</button></div></Modal>}

function DeleteModal({member,close,confirm}:{member:AccessUser;close:()=>void;confirm:()=>void}){const[armed,setArmed]=useState(false);return <Modal eyebrow="SUPER ADMIN ONLY" title="Delete team member" subtitle="This removes the login, permissions, sessions and direct chat history tied to this team identity." close={close}><div className="ix-v18-danger-zone"><span><Trash2 size={20}/></span><div><b>Delete {member.name} permanently?</b><p>This cannot be undone. Operational records assigned to this member will be unassigned where possible.</p></div></div><label className="ix-v18-confirm"><input type="checkbox" checked={armed} onChange={e=>setArmed(e.target.checked)}/><span>I understand this permanently removes the account.</span></label><div className="ix-modal-actions"><button className="ix-btn" onClick={close}>Cancel</button><button className="ix-btn ix-danger-final" disabled={!armed} onClick={confirm}><Trash2 size={14}/> Delete permanently</button></div></Modal>}

function Modal({eyebrow,title,subtitle,close,children,wide=false}:{eyebrow:string;title:string;subtitle?:string;close:()=>void;children:React.ReactNode;wide?:boolean}){useEffect(()=>{const h=(e:KeyboardEvent)=>e.key==='Escape'&&close();document.addEventListener('keydown',h);return()=>document.removeEventListener('keydown',h)},[close]);return <div className="ix-modal-backdrop" onMouseDown={close}><section className={`ix-modal ix-v18-modal ${wide?'wide':''}`} onMouseDown={e=>e.stopPropagation()}><header><div><span>{eyebrow}</span><h3>{title}</h3>{subtitle&&<p>{subtitle}</p>}</div><button onClick={close} aria-label="Close"><X size={18}/></button></header>{children}</section></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="ix-field"><span>{label}</span>{children}</label>}
function Actions({close,submit,disabled}:{close:()=>void;submit:string;disabled:boolean}){return <div className="ix-modal-actions wide"><button type="button" className="ix-btn" onClick={close}>Cancel</button><button className="ix-btn ix-primary" disabled={disabled}>{submit}</button></div>}
function moduleHelp(m:ModuleKey){return({leads:'Pipeline and prospect records',clients:'Client profiles and account data',projects:'Delivery projects',tasks:'Assigned operational work',content:'Content planning and publishing',invoices:'Billing and receivables',chat:'Team, client and direct conversations',reports:'Operational reporting',settings:'System settings'} as Record<ModuleKey,string>)[m]}
