import React,{useEffect,useMemo,useRef,useState}from'react';
import{ArrowLeft,AtSign,Building2,CheckCheck,MessageCircleMore,RefreshCw,Search,Send,Smile,Trash2,Users}from'lucide-react';
import{adminApi,type AppUser,type D1Result}from'./admin-api';
import'./chat-center-v12.css';
import'./chat-admin-v16.css';

type Conv={key:string;type:'general'|'client'|'dm';target_id:number|null;title:string;subtitle:string;avatar:string;last_message:string;last_at:string|null;last_sender:string|null;unread:number};
type Msg={id:number;user_id:number;client_id:number|null;recipient_user_id:number|null;message:string;created_at:string;user_name:string;user_role:string};
type ConvPayload={results:Conv[];total_unread:number};
const QUICK=['On it','Done','Need review','Waiting on client','Please check'];
const draftKey=(key:string)=>`idealab-chat-draft:${key}`;

export default function ChatCenterV12(){
 const[user,setUser]=useState<AppUser|null>(null),[convs,setConvs]=useState<Conv[]>([]),[channel,setChannel]=useState('general'),[messages,setMessages]=useState<Msg[]>([]),[text,setText]=useState(''),[query,setQuery]=useState(''),[conversationQuery,setConversationQuery]=useState(''),[loading,setLoading]=useState(true),[sending,setSending]=useState(false),[refreshing,setRefreshing]=useState(false),[deleting,setDeleting]=useState(false),[error,setError]=useState(''),[mobileConversation,setMobileConversation]=useState(false);
 const endRef=useRef<HTMLDivElement|null>(null),inputRef=useRef<HTMLTextAreaElement|null>(null),messageBoxRef=useRef<HTMLDivElement|null>(null),lastMessageId=useRef(0),firstLoad=useRef(true);
 const current=useMemo(()=>convs.find(c=>c.key===channel)||convs[0],[convs,channel]);
 const totalUnread=useMemo(()=>convs.reduce((n,c)=>n+Number(c.unread||0),0),[convs]);
 const superAdmin=user?.role==='super_admin';
 const nearBottom=()=>{const el=messageBoxRef.current;if(!el)return true;return el.scrollHeight-el.scrollTop-el.clientHeight<110};
 const scrollBottom=(smooth=false)=>window.setTimeout(()=>endRef.current?.scrollIntoView({behavior:smooth?'smooth':'auto',block:'end'}),20);
 const loadConversations=async(silent=false)=>{if(document.hidden&&silent)return;try{const c=await adminApi<ConvPayload>('/api/chat-v2/conversations');setConvs(c.results||[]);if(!(c.results||[]).some(x=>x.key===channel)&&c.results?.length)setChannel(c.results[0].key);if(!silent)setError('')}catch(e){if(!silent)setError(e instanceof Error?e.message:'Unable to load chat')}finally{if(!silent)setLoading(false)}};
 const loadMessages=async(silent=false,forceScroll=false)=>{if(!channel||(document.hidden&&silent))return;const shouldStick=forceScroll||nearBottom();try{const r=await adminApi<D1Result<Msg>>(`/api/chat-v2/messages?channel=${encodeURIComponent(channel)}`),next=r.results||[],newest=next.at(-1)?.id||0;setMessages(prev=>{const same=prev.length===next.length&&prev.at(-1)?.id===newest;return same?prev:next});if(newest!==lastMessageId.current){lastMessageId.current=newest;if(shouldStick)scrollBottom(!firstLoad.current&&!silent)}if(!silent)setError('')}catch(e){if(!silent)setError(e instanceof Error?e.message:'Unable to load messages')}finally{firstLoad.current=false}};
 const refreshAll=async()=>{setRefreshing(true);try{await Promise.all([loadConversations(),loadMessages(false,false)])}finally{setRefreshing(false)}};
 useEffect(()=>{let alive=true;adminApi<{user:AppUser}>('/api/me').then(r=>alive&&setUser(r.user)).catch(()=>{});void loadConversations();const timer=window.setInterval(()=>void loadConversations(true),30000);const vis=()=>{if(!document.hidden){void loadConversations(true);void loadMessages(true)}};document.addEventListener('visibilitychange',vis);return()=>{alive=false;clearInterval(timer);document.removeEventListener('visibilitychange',vis)}},[]);
 useEffect(()=>{firstLoad.current=true;lastMessageId.current=0;const saved=localStorage.getItem(draftKey(channel))||'';setText(saved);setQuery('');void loadMessages(false,true);const timer=window.setInterval(()=>void loadMessages(true),12000);return()=>window.clearInterval(timer)},[channel]);
 useEffect(()=>{const id=window.setTimeout(()=>localStorage.setItem(draftKey(channel),text),180);return()=>window.clearTimeout(id)},[text,channel]);
 const openChannel=(key:string)=>{setChannel(key);setMobileConversation(true);setTimeout(()=>inputRef.current?.focus(),120)};
 const send=async(message=text.trim())=>{if(!message||sending)return;setSending(true);setError('');try{await adminApi('/api/chat-v2/messages',{method:'POST',body:JSON.stringify({channel,message})});setText('');localStorage.removeItem(draftKey(channel));await Promise.all([loadMessages(false,true),loadConversations(true)]);setTimeout(()=>inputRef.current?.focus(),40)}catch(e){setError(e instanceof Error?e.message:'Unable to send message')}finally{setSending(false)}};
 const deleteMessage=async(id:number)=>{if(!superAdmin||deleting)return;if(!window.confirm('Delete this message permanently? This cannot be undone.'))return;setDeleting(true);setError('');try{await adminApi(`/api/chat-v2/messages/${id}`,{method:'DELETE',body:JSON.stringify({channel})});await Promise.all([loadMessages(false,false),loadConversations(true)])}catch(e){setError(e instanceof Error?e.message:'Unable to delete message')}finally{setDeleting(false)}};
 const clearConversation=async()=>{if(!superAdmin||deleting||!current)return;if(!window.confirm(`Delete all messages in ${current.title}? This permanently clears this conversation for everyone.`))return;setDeleting(true);setError('');try{await adminApi('/api/chat-v2/conversation',{method:'DELETE',body:JSON.stringify({channel})});setMessages([]);lastMessageId.current=0;await loadConversations(true)}catch(e){setError(e instanceof Error?e.message:'Unable to clear conversation')}finally{setDeleting(false)}};
 const filteredConvs=useMemo(()=>{const q=conversationQuery.trim().toLowerCase();return convs.filter(c=>!q||`${c.title} ${c.subtitle} ${c.last_message}`.toLowerCase().includes(q))},[convs,conversationQuery]);
 const filteredMsgs=useMemo(()=>{const q=query.trim().toLowerCase();return messages.filter(m=>!q||`${m.user_name} ${m.message}`.toLowerCase().includes(q))},[messages,query]);
 const sections={general:filteredConvs.filter(c=>c.type==='general'),clients:filteredConvs.filter(c=>c.type==='client'),people:filteredConvs.filter(c=>c.type==='dm')};
 return <div className="il-chat-center-v12"><header className="il-chat-center-top"><button className="il-chat-back" onClick={()=>location.assign('/admin')}><ArrowLeft size={18}/></button><div><small>IDEA LAB / COLLABORATION</small><h1>Chat Center</h1></div><div className="il-chat-top-tools"><button className="il-chat-refresh" onClick={()=>void refreshAll()} disabled={refreshing} title="Refresh chat"><RefreshCw size={15}/></button><div className="il-chat-top-status"><span/><b>{totalUnread}</b><small>unread</small></div></div></header>
  <main className={`il-chat-layout ${mobileConversation?'show-conversation':''}`}>
   <aside className="il-chat-sidebar"><div className="il-chat-sidebar-head"><div><h2>Conversations</h2><span>Team, clients and direct chats</span></div><label><Search size={15}/><input value={conversationQuery} onChange={e=>setConversationQuery(e.target.value)} placeholder="Search chats…"/></label></div>
    <div className="il-chat-conv-list">{loading&&<div className="il-chat-list-empty">Loading conversations…</div>}<ConversationSection title="Team" icon={<Users size={13}/>} rows={sections.general} channel={channel} onOpen={openChannel}/><ConversationSection title="Clients" icon={<Building2 size={13}/>} rows={sections.clients} channel={channel} onOpen={openChannel}/><ConversationSection title="Direct messages" icon={<AtSign size={13}/>} rows={sections.people} channel={channel} onOpen={openChannel}/>{!loading&&!filteredConvs.length&&<div className="il-chat-list-empty">No matching conversations.</div>}</div>
   </aside>
   <section className="il-chat-thread">{current?<><header className="il-chat-thread-head"><button className="il-chat-mobile-back" onClick={()=>setMobileConversation(false)}><ArrowLeft size={17}/></button><div className={`il-chat-avatar type-${current.type}`}>{current.avatar}</div><div className="il-chat-thread-title"><h2>{current.title}</h2><span>{current.subtitle}</span></div><div className="il-chat-thread-actions"><label className="il-chat-thread-search"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search this chat"/></label>{superAdmin&&<button className="il-chat-clear" disabled={deleting||messages.length===0} onClick={()=>void clearConversation()} title="Clear chat history"><Trash2 size={15}/><span>Clear chat</span></button>}</div></header>
    <div className="il-chat-quick-row">{QUICK.map(q=><button key={q} disabled={sending} onClick={()=>void send(q)}>{q}</button>)}</div>
    <div className="il-chat-message-area" ref={messageBoxRef}>{filteredMsgs.map((m,i)=>{const mine=m.user_id===user?.id,prev=filteredMsgs[i-1],newGroup=!prev||prev.user_id!==m.user_id||new Date(m.created_at).getTime()-new Date(prev.created_at).getTime()>8*60*1000;return <div key={m.id} className={`il-chat-message ${mine?'mine':''}`}>{newGroup&&<div className="il-chat-message-author"><span>{m.user_name.slice(0,1).toUpperCase()}</span><div><b>{mine?'You':m.user_name}</b><small>{m.user_role.replaceAll('_',' ')}</small></div></div>}<div className="il-chat-bubble"><p>{m.message}</p><div className="il-chat-bubble-meta"><time>{new Date(m.created_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}{mine&&<CheckCheck size={11}/>}</time>{superAdmin&&<button className="il-chat-delete-message" disabled={deleting} onClick={()=>void deleteMessage(m.id)} title="Delete message"><Trash2 size={12}/></button>}</div></div></div>})}{!filteredMsgs.length&&<div className="il-chat-thread-empty"><MessageCircleMore size={28}/><b>{query?'No matching messages':'Start this conversation'}</b><span>{query?'Try another search.':'Send an update, question or quick reply.'}</span></div>}<div ref={endRef}/></div>
    {error&&<div className="il-chat-center-error">{error}<button onClick={()=>void refreshAll()}>Retry</button></div>}<div className="il-chat-composer"><div className="il-chat-compose-box"><button type="button" title="Mention" onClick={()=>setText(v=>v+'@')}><AtSign size={17}/></button><textarea ref={inputRef} rows={1} value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send()}}} placeholder={`Message ${current.title}…`}/><button type="button" title="Emoji" onClick={()=>setText(v=>v+' 🙂')}><Smile size={17}/></button><button type="button" className="send" disabled={!text.trim()||sending} onClick={()=>void send()}><Send size={17}/></button></div><small>{deleting?'Updating chat…':sending?'Sending…':'Drafts save automatically · Enter to send'}</small></div></>:<div className="il-chat-thread-empty"><MessageCircleMore size={32}/><b>Select a conversation</b></div>}</section>
  </main>
 </div>;
}

function ConversationSection({title,icon,rows,channel,onOpen}:{title:string;icon:React.ReactNode;rows:Conv[];channel:string;onOpen:(key:string)=>void}){if(!rows.length)return null;return <section className="il-chat-conv-section"><h3>{icon}{title}<span>{rows.length}</span></h3>{rows.map(c=><button key={c.key} className={`il-chat-conv ${channel===c.key?'active':''}`} onClick={()=>onOpen(c.key)}><div className={`il-chat-avatar type-${c.type}`}>{c.avatar}</div><div className="il-chat-conv-copy"><div><b>{c.title}</b>{c.last_at&&<time>{formatWhen(c.last_at)}</time>}</div><p>{c.last_message?(c.last_sender?`${c.last_sender}: ${c.last_message}`:c.last_message):c.subtitle}</p></div>{c.unread>0&&<span className="il-chat-unread">{Math.min(c.unread,99)}</span>}</button>)}</section>}
function formatWhen(value:string){const d=new Date(value),now=new Date();if(d.toDateString()===now.toDateString())return d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});return d.toLocaleDateString([],{month:'short',day:'numeric'})}
