import React, { useEffect, useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import { useLocation } from 'react-router-dom';
import { FileDown } from 'lucide-react';
import { jsPDF } from 'jspdf';
import { adminApi, type D1Result } from './admin-api';
import './invoice-pdf-support.css';

type InvoiceRow = {
  id:number; client_id:number; client_name?:string|null; invoice_no:string; status:string; amount:number; currency:string;
  due_date:string|null; paid_at:string|null; notes:string|null; created_at?:string|null; subtotal?:number;
  discount_type?:'none'|'percent'|'fixed'; discount_value?:number; discount_amount?:number;
};
type InvoiceItem={id?:number;invoice_id?:number;service_id?:number|null;description:string;quantity:number;unit_price:number;line_total:number;sort_order?:number};
type InvoiceDetail={invoice:InvoiceRow;items:InvoiceItem[]};
type ClientRow={id:number;name:string;company:string|null;email:string|null;phone:string|null;country:string|null};
type PortalTarget={invoice:InvoiceRow;element:HTMLElement};

function money(value:number,currency:string){try{return new Intl.NumberFormat('en',{style:'currency',currency,currencyDisplay:'code',minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(value||0))}catch{return `${currency} ${Number(value||0).toFixed(2)}`}}
function dateLabel(value?:string|null){if(!value)return'-';const d=new Date(value);if(Number.isNaN(d.getTime()))return value.slice(0,10);return new Intl.DateTimeFormat('en',{day:'2-digit',month:'short',year:'numeric'}).format(d)}
function safeFilename(value:string){return value.replace(/[^a-z0-9._-]+/gi,'-').replace(/-+/g,'-').replace(/^-|-$/g,'')}
async function loadLogoDataUrl(){try{const r=await fetch('/idealab-logo.jpg',{cache:'force-cache'});if(!r.ok)return null;const blob=await r.blob();return await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result||''));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob)})}catch{return null}}

async function generateInvoicePdf(detail:InvoiceDetail,client?:ClientRow){
 const invoice=detail.invoice;const items=detail.items?.length?detail.items:[{description:'Professional services',quantity:1,unit_price:Number(invoice.amount||0),line_total:Number(invoice.amount||0)}];
 const doc=new jsPDF({unit:'mm',format:'a4',orientation:'portrait'});const w=doc.internal.pageSize.getWidth();const h=doc.internal.pageSize.getHeight();const m=18;const right=w-m;const dark='#111318';const muted='#69707A';const border='#E5E7EB';const soft='#F6F7F9';
 doc.setFillColor(dark);doc.rect(0,0,w,43,'F');const logo=await loadLogoDataUrl();if(logo){try{doc.addImage(logo,'JPEG',m,10,23,23,undefined,'FAST')}catch{}}
 doc.setTextColor('#FFFFFF');doc.setFont('helvetica','bold');doc.setFontSize(18);doc.text('IDEA LAB',logo?m+29:m,20);doc.setFont('helvetica','normal');doc.setFontSize(8.5);doc.text('Creative & Digital Operations',logo?m+29:m,27);doc.setFont('helvetica','bold');doc.setFontSize(22);doc.text('INVOICE',right,18,{align:'right'});doc.setFontSize(9);doc.setFont('helvetica','normal');doc.text(invoice.invoice_no,right,25,{align:'right'});doc.text(invoice.status.replaceAll('_',' ').toUpperCase(),right,31,{align:'right'});
 let y=57;doc.setTextColor(muted);doc.setFontSize(8.5);doc.setFont('helvetica','bold');doc.text('BILL TO',m,y);doc.text('INVOICE DETAILS',118,y);y+=7;doc.setTextColor(dark);doc.setFontSize(11.5);doc.text(client?.name||invoice.client_name||'Client',m,y);doc.setFontSize(9);doc.setFont('helvetica','normal');for(const line of [client?.company,client?.email,client?.phone,client?.country].filter(Boolean) as string[]){y+=5;doc.text(line,m,y)}
 const dy=64;doc.setTextColor(muted);doc.setFontSize(9);doc.text('Issue date',118,dy);doc.text('Due date',118,dy+7);doc.text('Currency',118,dy+14);doc.text('Status',118,dy+21);doc.setTextColor(dark);doc.setFont('helvetica','bold');doc.text(dateLabel(invoice.created_at),right,dy,{align:'right'});doc.text(dateLabel(invoice.due_date),right,dy+7,{align:'right'});doc.text((invoice.currency||'USD').toUpperCase(),right,dy+14,{align:'right'});doc.text(invoice.status.replaceAll('_',' '),right,dy+21,{align:'right'});
 let tableY=Math.max(105,y+17);const header=()=>{doc.setFillColor(soft);doc.roundedRect(m,tableY,w-m*2,12,2,2,'F');doc.setTextColor(muted);doc.setFont('helvetica','bold');doc.setFontSize(8.2);doc.text('SERVICE',m+5,tableY+7.5);doc.text('QTY',127,tableY+7.5,{align:'right'});doc.text('UNIT PRICE',156,tableY+7.5,{align:'right'});doc.text('TOTAL',right-4,tableY+7.5,{align:'right'});tableY+=19};header();
 for(const item of items){if(tableY>230){doc.addPage();tableY=20;header()}const descLines=doc.splitTextToSize(item.description||'Service',80) as string[];const rowHeight=Math.max(11,descLines.length*4.2+4);doc.setTextColor(dark);doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text(descLines,m+5,tableY);doc.setFont('helvetica','normal');doc.text(String(Number(item.quantity||0)),127,tableY,{align:'right'});doc.text(money(item.unit_price,invoice.currency||'USD'),156,tableY,{align:'right'});doc.text(money(item.line_total??item.quantity*item.unit_price,invoice.currency||'USD'),right-4,tableY,{align:'right'});doc.setDrawColor(border);doc.line(m,tableY+rowHeight-2,right,tableY+rowHeight-2);tableY+=rowHeight}
 const subtotal=Number(invoice.subtotal??items.reduce((s,i)=>s+Number(i.line_total||i.quantity*i.unit_price),0));const discountAmount=Number(invoice.discount_amount||0);const total=Number(invoice.amount||Math.max(0,subtotal-discountAmount));let totalY=tableY+8;if(totalY>245){doc.addPage();totalY=25}
 doc.setTextColor(muted);doc.setFontSize(9);doc.text('Subtotal',130,totalY);doc.setTextColor(dark);doc.text(money(subtotal,invoice.currency||'USD'),right,totalY,{align:'right'});if(discountAmount>0){totalY+=8;doc.setTextColor(muted);const label=invoice.discount_type==='percent'?`Discount (${Number(invoice.discount_value||0)}%)`:'Discount';doc.text(label,130,totalY);doc.setTextColor(dark);doc.text(`- ${money(discountAmount,invoice.currency||'USD')}`,right,totalY,{align:'right'})}totalY+=11;doc.setFont('helvetica','bold');doc.setFontSize(13);doc.text('Total',130,totalY);doc.text(money(total,invoice.currency||'USD'),right,totalY,{align:'right'});
 let notesY=totalY+18;if(invoice.notes?.trim()){doc.setFillColor(soft);const lines=doc.splitTextToSize(invoice.notes.trim(),w-m*2-10) as string[];const nh=Math.max(24,14+lines.length*4.5);if(notesY+nh>h-35){doc.addPage();notesY=22}doc.roundedRect(m,notesY,w-m*2,nh,2,2,'F');doc.setTextColor(muted);doc.setFont('helvetica','bold');doc.setFontSize(8.5);doc.text('NOTES',m+5,notesY+7);doc.setFont('helvetica','normal');doc.setTextColor(dark);doc.text(lines,m+5,notesY+14);notesY+=nh+8}
 if(invoice.status==='paid'&&invoice.paid_at){doc.setTextColor('#18794E');doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text(`PAID - ${dateLabel(invoice.paid_at)}`,m,Math.min(notesY+3,h-32))}
 doc.setDrawColor(border);doc.line(m,h-27,right,h-27);doc.setTextColor(muted);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.text('Thank you for working with IDEA LAB.',m,h-18);doc.text(`Invoice ${invoice.invoice_no}`,right,h-18,{align:'right'});doc.save(`${safeFilename(invoice.invoice_no||`invoice-${invoice.id}`)}.pdf`)
}

function mountTarget(container:HTMLElement,invoice:InvoiceRow,targets:PortalTarget[]){let mount=container.querySelector<HTMLElement>('[data-invoice-pdf-mount]');if(!mount){mount=document.createElement('span');mount.dataset.invoicePdfMount='true';mount.className='il-invoice-pdf-mount';container.appendChild(mount)}targets.push({invoice,element:mount})}
function findInvoiceTargets(invoices:InvoiceRow[]){const byNo=new Map(invoices.map(i=>[i.invoice_no.trim(),i]));const targets:PortalTarget[]=[];const seen=new Set<number>();for(const card of Array.from(document.querySelectorAll<HTMLElement>('.il-v2-card-list article'))){const no=card.querySelector('b')?.textContent?.trim();const inv=no?byNo.get(no):undefined;if(!inv||seen.has(inv.id))continue;const children=Array.from(card.children).filter((n):n is HTMLElement=>n instanceof HTMLElement);const actions=children[children.length-1];if(!actions)continue;mountTarget(actions,inv,targets);seen.add(inv.id)}return targets}

export default function InvoicePdfSupport(){const location=useLocation();const[invoices,setInvoices]=useState<InvoiceRow[]>([]);const[clients,setClients]=useState<ClientRow[]>([]);const[targets,setTargets]=useState<PortalTarget[]>([]);const[generatingId,setGeneratingId]=useState<number|null>(null);const clientMap=useMemo(()=>new Map(clients.map(c=>[c.id,c])),[clients]);
 useEffect(()=>{if(location.pathname!=='/admin/invoices'){setInvoices([]);setClients([]);setTargets([]);return}let active=true;const load=()=>Promise.all([adminApi<D1Result<InvoiceRow>>('/api/invoices'),adminApi<D1Result<ClientRow>>('/api/clients')]).then(([i,c])=>{if(active){setInvoices(i.results||[]);setClients(c.results||[])}}).catch(()=>{if(active){setInvoices([]);setClients([])}});void load();const refresh=()=>void load();window.addEventListener('idealab:invoice-saved',refresh);return()=>{active=false;window.removeEventListener('idealab:invoice-saved',refresh)}},[location.pathname]);
 useEffect(()=>{if(location.pathname!=='/admin/invoices')return;const sync=()=>setTargets(findInvoiceTargets(invoices));const t=window.setTimeout(sync,50);const o=new MutationObserver(sync);o.observe(document.body,{childList:true,subtree:true});return()=>{clearTimeout(t);o.disconnect()}},[location.pathname,invoices]);
 const download=async(invoice:InvoiceRow)=>{if(generatingId!==null)return;setGeneratingId(invoice.id);try{const detail=await adminApi<InvoiceDetail>(`/api/invoices/${invoice.id}/detail`);await generateInvoicePdf(detail,clientMap.get(invoice.client_id))}catch(error){console.error('Invoice PDF generation failed',error);window.alert('PDF generation failed. Please try again.')}finally{setGeneratingId(null)}};
 return <>{targets.map(({invoice,element})=>createPortal(<button key={invoice.id} type="button" className="il-admin-button il-invoice-pdf-button" onClick={()=>void download(invoice)} disabled={generatingId===invoice.id} title="Download PDF invoice"><FileDown size={15}/><span>{generatingId===invoice.id?'Generating…':'PDF'}</span></button>,element))}</>}
