import React, { useEffect, useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import { useLocation } from 'react-router-dom';
import { AlertTriangle, CalendarClock, CheckCircle2, Filter, LayoutGrid, List, Plus, Search, Trash2, UserRound } from 'lucide-react';
import { adminApi, type AppUser, type D1Result } from './admin-api';
import './tasks-workspace-v9.css';

type TaskRow={id:number;title:string;description?:string|null;status:string;priority:string;client_id:number|null;client_name?:string|null;project_id:number|null;project_name?:string|null;assigned_user_id:number|null;assignee_name?:string|null;created_by_name?:string|null;due_at:string|null;checklist_json?:string};
type ClientRow={id:number;name:string};
type ViewMode='board'|'list';

const STATUSES=['todo','in_progress','review','done'] as const;
const PRIORITIES=['low','medium','high','urgent'] as const;

function when(v:string|null){if(!v)return'No due date';const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat('en',{day:'numeric',month:'short',year:'numeric'}).format(d)}
function isOverdue(t:TaskRow){return !!t.due_at&&!['done','cancelled'].includes(t.status)&&new Date(t.due_at).getTime()<Date.now()}
function isToday(t:TaskRow){if(!t.due_at)return false;const d=new Date(t.due_at),n=new Date();return d.toDateString()===n.toDateString()}

export default function TasksWorkspaceV9(){
 const location=useLocation();const active=location.pathname==='/admin/tasks';
 const[target,setTarget]=useState<Element|null>(null);const[user,setUser]=useState<AppUser|null>(null);const[rows,setRows]=useState<TaskRow[]>([]);const[clients,setClients]=useState<ClientRow[]>([]);const[users,setUsers]=useState<AppUser[]>([]);const[query,setQuery]=useState('');const[clientFilter,setClientFilter]=useState('all');const[assigneeFilter,setAssigneeFilter]=useState('all');const[priorityFilter,setPriorityFilter]=useState('all');const[view,setView]=useState<ViewMode>('board');const[selected,setSelected]=useState<number[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 const superAdmin=user?.role==='super_admin';
 useEffect(()=>{if(!active){document.documentElement.classList.remove('il-taskv9-active');setTarget(null);return}document.documentElement.classList.add('il-taskv9-active');const find=()=>setTarget(document.querySelector('.il-premium-content'));find();const o=new MutationObserver(find);o.observe(document.body,{childList:true,subtree:true});return()=>{o.disconnect();document.documentElement.classList.remove('il-taskv9-active')}} , [active]);
 const load=async()=>{if(!active)return;setBusy(true);setError('');try{const me=await adminApi<{user:AppUser}>('/api/me');setUser(me.user);const all=me.user.role==='super_admin';const[t,c,u]=await Promise.all([adminApi<D1Result<TaskRow>>('/api/tasks'),adminApi<D1Result<ClientRow>>('/api/clients'),all?adminApi<D1Result<AppUser>>('/api/users'):Promise.resolve({results:[] as AppUser[]})]);setRows(t.results||[]);setClients(c.results||[]);setUsers(u.results||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load tasks')}finally{setBusy(false)}};
 useEffect(()=>{void load()},[active]);
 const filtered=useMemo(()=>rows.filter(r=>{if(clientFilter!=='all'&&String(r.client_id)!==clientFilter)return false;if(superAdmin&&assigneeFilter!=='all'&&String(r.assigned_user_id)!==assigneeFilter)return false;if(priorityFilter!=='all'&&r.priority!==priorityFilter)return false;const q=query.trim().toLowerCase();return !q||`${r.title} ${r.description||''} ${r.client_name||''} ${r.project_name||''} ${r.assignee_name||''}`.toLowerCase().includes(q)}),[rows,query,clientFilter,assigneeFilter,priorityFilter,superAdmin]);
 const openCount=rows.filter(r=>!['done','cancelled'].includes(r.status)).length, overdue=rows.filter(isOverdue).length,today=rows.filter(isToday).length,urgent=rows.filter(r=>r.priority==='urgent'&&!['done','cancelled'].includes(r.status)).length;
 const quickStatus=async(row:TaskRow,status:string)=>{try{await adminApi(`/api/tasks/${row.id}`,{method:'PATCH',body:JSON.stringify({status})});setRows(v=>v.map(x=>x.id===row.id?{...x,status}:x))}catch(e){setError(e instanceof Error?e.message:'Update failed')}};
 const toggleAll=()=>setSelected(filtered.length&&filtered.every(r=>selected.includes(r.id))?[]:filtered.map(r=>r.id));
 const bulkStatus=async(status:string)=>{if(!selected.length)return;setBusy(true);try{await adminApi('/api/bulk',{method:'POST',body:JSON.stringify({entity:'tasks',ids:selected,action:'status',status})});setSelected([]);await load()}catch(e){setError(e instanceof Error?e.message:'Bulk update failed')}finally{setBusy(false)}};
 const bulkDelete=async()=>{if(!superAdmin||!selected.length)return;if(!confirm(`Delete ${selected.length} selected task${selected.length===1?'':'s'}?`))return;setBusy(true);try{await adminApi('/api/bulk',{method:'POST',body:JSON.stringify({entity:'tasks',ids:selected,action:'delete'})});setSelected([]);await load()}catch(e){setError(e instanceof Error?e.message:'Delete failed')}finally{setBusy(false)}};
 if(!active||!target)return null;
 return createPortal(<section className="il-taskv9-root">
  <div className="il-taskv9-heading"><div><span>TEAM EXECUTION</span><h2>{superAdmin?'Task control center':'My tasks'}</h2><p>{superAdmin?'See all work, identify blockers, and reassign quickly.':'Only work assigned to your account is shown here.'}</p></div><div className="il-taskv9-actions"><button className="il-admin-button il-admin-primary" onClick={()=>window.dispatchEvent(new CustomEvent('idealab:new-task'))}><Plus size={15}/> Add task</button></div></div>
  <div className="il-taskv9-stats"><Stat label="Open" value={openCount}/><Stat label="Due today" value={today}/><Stat label="Overdue" value={overdue} tone="danger"/><Stat label="Urgent" value={urgent} tone="warn"/></div>
  {!!error&&<div className="il-taskv9-error"><AlertTriangle size={15}/>{error}</div>}
  <div className="il-taskv9-toolbar"><label><Search size={15}/><input placeholder="Search tasks, clients, assignees…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select value={clientFilter} onChange={e=>setClientFilter(e.target.value)}><option value="all">All clients</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>{superAdmin&&<select value={assigneeFilter} onChange={e=>setAssigneeFilter(e.target.value)}><option value="all">All assignees</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select>}<select value={priorityFilter} onChange={e=>setPriorityFilter(e.target.value)}><option value="all">All priorities</option>{PRIORITIES.map(p=><option key={p}>{p}</option>)}</select><div className="il-taskv9-view"><button className={view==='board'?'active':''} onClick={()=>setView('board')}><LayoutGrid size={14}/> Board</button><button className={view==='list'?'active':''} onClick={()=>setView('list')}><List size={14}/> List</button></div></div>
  <div className="il-taskv9-select"><label><input type="checkbox" checked={!!filtered.length&&filtered.every(r=>selected.includes(r.id))} onChange={toggleAll}/> Select visible</label><span>{filtered.length} shown</span>{selected.length>0&&<b>{selected.length} selected</b>}</div>
  {selected.length>0&&<div className="il-taskv9-bulk"><div><Filter size={14}/><b>Bulk actions</b></div><div>{STATUSES.map(s=><button key={s} disabled={busy} onClick={()=>void bulkStatus(s)}>{s.replaceAll('_',' ')}</button>)}{superAdmin&&<button className="danger" onClick={()=>void bulkDelete()}><Trash2 size={14}/> Delete</button>}</div></div>}
  {busy&&!rows.length?<div className="il-taskv9-loading">Loading tasks…</div>:view==='board'?<div className="il-taskv9-board">{STATUSES.map(status=><section key={status}><header><b>{status.replaceAll('_',' ')}</b><span>{filtered.filter(r=>r.status===status).length}</span></header><div>{filtered.filter(r=>r.status===status).map(r=><TaskCard key={r.id} row={r} selected={selected.includes(r.id)} onSelect={v=>setSelected(s=>v?[...new Set([...s,r.id])]:s.filter(id=>id!==r.id))} onStatus={s=>void quickStatus(r,s)}/>)}</div></section>)}</div>:<div className="il-taskv9-list"><div className="il-taskv9-list-head"><span></span><b>Task</b><b>Client</b><b>Assignee</b><b>Priority</b><b>Due</b><b>Status</b></div>{filtered.map(r=><div className="il-taskv9-list-row" key={r.id}><input type="checkbox" checked={selected.includes(r.id)} onChange={e=>setSelected(s=>e.target.checked?[...new Set([...s,r.id])]:s.filter(id=>id!==r.id))}/><div><b>{r.title}</b><small>{r.description||r.project_name||'No description'}</small></div><span>{r.client_name||'Internal'}</span><span>{r.assignee_name||'Unassigned'}</span><span className={`priority ${r.priority}`}>{r.priority}</span><span className={isOverdue(r)?'overdue':''}>{when(r.due_at)}</span><select value={r.status} onChange={e=>void quickStatus(r,e.target.value)}>{STATUSES.map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></div>)}</div>}
 </section>,target)
}

function Stat({label,value,tone}:{label:string;value:number;tone?:string}){return <div className={`il-taskv9-stat ${tone||''}`}><small>{label}</small><b>{value}</b></div>}
function TaskCard({row,selected,onSelect,onStatus}:{row:TaskRow;selected:boolean;onSelect:(v:boolean)=>void;onStatus:(s:string)=>void}){return <article className={`il-taskv9-card ${selected?'selected':''}`}><div className="il-taskv9-card-top"><label><input type="checkbox" checked={selected} onChange={e=>onSelect(e.target.checked)}/></label><span className={`priority ${row.priority}`}>{row.priority}</span>{isOverdue(row)&&<span className="overdue">Overdue</span>}</div><h4>{row.title}</h4>{row.description&&<p>{row.description}</p>}<div className="il-taskv9-meta"><span><UserRound size={12}/>{row.assignee_name||'Unassigned'}</span><span>{row.client_name||'Internal'}</span></div><div className="il-taskv9-foot"><span><CalendarClock size={12}/>{when(row.due_at)}</span><select value={row.status} onChange={e=>onStatus(e.target.value)}>{STATUSES.map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></div></article>}
