import React, { useEffect, useMemo, useState } from 'react';
import { Check, Copy, Eye, EyeOff, Sparkles, X } from 'lucide-react';
import { adminApi, type Role } from './admin-api';
import './team-experience-v12.css';
import './team-fixes-v14.css';

type ModuleKey='leads'|'clients'|'projects'|'tasks'|'invoices'|'content'|'reports'|'settings'|'chat';
type AccessMap=Record<ModuleKey,boolean>&{all_clients:boolean};
type AccessUser={id:number;name:string;email:string;role:Role;active:number;access:AccessMap;client_ids:number[]};
type ClientRow={id:number;name:string;company?:string|null};
type Toast={id:number;text:string;error?:boolean};

const ROLE_HINTS:Record<Exclude<Role,'super_admin'>,string>={
  admin:'Operations lead — broad access to clients, projects, tasks, content, invoices and reports.',
  sales:'Sales — leads and client records, with no finance or delivery modules by default.',
  project_manager:'Project manager — clients, projects, tasks and content delivery.',
  finance:'Finance — clients, invoices and financial reports.',
  content:'Content — clients and content planning.'
};
const MODULE_LABELS:Record<ModuleKey,string>={leads:'Leads',clients:'Clients',projects:'Projects',tasks:'Tasks',invoices:'Invoices',content:'Content',reports:'Reports',settings:'Settings',chat:'Team chat'};
const MODULES:(Exclude<ModuleKey,'settings'>)[]=['leads','clients','projects','tasks','invoices','content','reports','chat'];

function passwordValue(){const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%';const bytes=crypto.getRandomValues(new Uint8Array(14));return Array.from(bytes,b=>alphabet[b%alphabet.length]).join('')}
function Modal({children,onClose,access=false}:{children:React.ReactNode;onClose:()=>void;access?:boolean}){useEffect(()=>{const h=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose()};document.addEventListener('keydown',h);return()=>document.removeEventListener('keydown',h)},[onClose]);return <div className="il-v4-modal-backdrop" onMouseDown={onClose} role="presentation"><div className={access?'il-team-access-modal-v12':'il-team-modal-v12'} onMouseDown={e=>e.stopPropagation()} role="dialog" aria-modal="true">{children}</div></div>}
function ModalHead({title,onClose}:{title:string;onClose:()=>void}){return <header><div><span>TEAM CONTROL</span><h3>{title}</h3></div><button type="button" aria-label="Close" onClick={onClose}><X size={19}/></button></header>}

export default function TeamExperienceV12(){
  const[createOpen,setCreateOpen]=useState(false);const[accessUser,setAccessUser]=useState<AccessUser|null>(null);const[toasts,setToasts]=useState<Toast[]>([]);
  const toast=(text:string,error=false)=>{const id=Date.now()+Math.random();setToasts(v=>[...v,{id,text,error}]);window.setTimeout(()=>setToasts(v=>v.filter(x=>x.id!==id)),3600)};
  useEffect(()=>{const capture=(event:MouseEvent)=>{const target=event.target as HTMLElement|null;const button=target?.closest('button');if(!button)return;const text=(button.textContent||'').trim().toLowerCase();if(text==='add user'||text==='add team member'){event.preventDefault();event.stopPropagation();setCreateOpen(true);return}if(text.includes('manage access')){const card=button.closest('article');const email=(card?.querySelector('.il-v4-user-head small')?.textContent||'').trim().toLowerCase();if(!email)return;event.preventDefault();event.stopPropagation();void adminApi<{results:AccessUser[]}>('/api/access/users').then(r=>{const user=(r.results||[]).find(x=>x.email.toLowerCase()===email);if(user)setAccessUser(user);else toast('Could not find that team account.',true)}).catch(e=>toast(e instanceof Error?e.message:'Could not load access.',true))}};document.addEventListener('click',capture,true);return()=>document.removeEventListener('click',capture,true)},[]);
  return <>{createOpen&&<CreateTeamModal onClose={()=>setCreateOpen(false)} onCreated={user=>{setCreateOpen(false);setAccessUser(user);toast(`${user.name} was created. Now choose access.`)}} toast={toast}/>} {accessUser&&<AccessManager user={accessUser} onClose={()=>setAccessUser(null)} onSaved={()=>{toast(`Access saved for ${accessUser.name}.`);setAccessUser(null);window.setTimeout(()=>window.location.reload(),550)}} toast={toast}/>}<div className="il-team-toast-host" aria-live="polite">{toasts.map(t=><div key={t.id} className={`il-team-toast ${t.error?'error':''}`}>{t.text}</div>)}</div></>
}

function CreateTeamModal({onClose,onCreated,toast}:{onClose:()=>void;onCreated:(u:AccessUser)=>void;toast:(t:string,e?:boolean)=>void}){
  const[form,setForm]=useState({name:'',email:'',role:'sales' as Exclude<Role,'super_admin'>,password:''});const[showPassword,setShowPassword]=useState(false);const[saving,setSaving]=useState(false);const[error,setError]=useState('');
  const valid=form.name.trim().length>=2&&/^\S+@\S+\.\S+$/.test(form.email.trim())&&form.password.length>=8;
  const generate=()=>{const p=passwordValue();setForm(v=>({...v,password:p}));setShowPassword(true)};
  const copy=async()=>{if(!form.password)return;try{await navigator.clipboard?.writeText(form.password);toast('Password copied.')}catch{toast('Copy was blocked by this browser. Select the password and copy it manually.',true)}};
  const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!valid){setError('Add a name, a valid email, and a password with at least 8 characters.');return}setSaving(true);setError('');try{await adminApi('/api/users',{method:'POST',body:JSON.stringify({...form,name:form.name.trim(),email:form.email.trim().toLowerCase()})});const result=await adminApi<{results:AccessUser[]}>('/api/access/users');const created=(result.results||[]).find(u=>u.email.toLowerCase()===form.email.trim().toLowerCase());if(!created)throw new Error('Account was created, but access setup could not be opened. Refresh and use Manage access.');onCreated(created)}catch(err){setError(err instanceof Error?err.message:'Could not create this account.')}finally{setSaving(false)}};
  return <Modal onClose={onClose}><ModalHead title="Add a team member" onClose={onClose}/><div className="il-team-create-guide"><div><strong>Create the login first, then choose exactly what they can access.</strong><small>You will be taken straight to client and module permissions after creation.</small></div><div className="il-team-flow"><b>1 Account</b><i>→</i><span>2 Access</span><i>→</i><span>3 Ready</span></div></div><form className="il-v4-form" onSubmit={submit} noValidate><label>Full name *<input autoFocus autoComplete="name" placeholder="e.g. Kashaf Ali" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email *<input type="email" autoComplete="email" placeholder="name@company.com" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label data-role-hint={ROLE_HINTS[form.role]}>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value as Exclude<Role,'super_admin'>})}><option value="admin">Admin</option><option value="sales">Sales</option><option value="project_manager">Project manager</option><option value="finance">Finance</option><option value="content">Content</option></select></label><label data-password-hint="Use at least 8 characters. Generate a strong temporary password and share it securely.">Temporary password *<input type={showPassword?'text':'password'} autoComplete="new-password" placeholder="Minimum 8 characters" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><span className="il-password-tools"><button type="button" onClick={()=>setShowPassword(v=>!v)}>{showPassword?<><EyeOff size={12}/> Hide</>:<><Eye size={12}/> Show</>}</button><button type="button" onClick={generate}><Sparkles size={12}/> Generate</button><button type="button" disabled={!form.password} onClick={()=>void copy()}><Copy size={12}/> Copy</button></span></label>{error&&<div className="il-team-api-error">{error}</div>}<div className="wide il-v4-modal-actions"><button type="button" className="il-admin-button" onClick={onClose}>Cancel</button><button className="il-admin-button il-admin-primary" disabled={!valid||saving}>{saving?'Creating…':'Create & set access'}</button></div></form></Modal>
}

function AccessManager({user,onClose,onSaved,toast}:{user:AccessUser;onClose:()=>void;onSaved:()=>void;toast:(t:string,e?:boolean)=>void}){
  const[access,setAccess]=useState({...user.access});const[selected,setSelected]=useState<number[]>(user.client_ids||[]);const[clients,setClients]=useState<ClientRow[]>([]);const[query,setQuery]=useState('');const[saving,setSaving]=useState(false);const[error,setError]=useState('');
  useEffect(()=>{void adminApi<{results:ClientRow[]}>('/api/clients').then(r=>setClients(r.results||[])).catch(e=>setError(e instanceof Error?e.message:'Could not load clients.'))},[]);
  const filtered=useMemo(()=>clients.filter(c=>`${c.name} ${c.company||''}`.toLowerCase().includes(query.toLowerCase())),[clients,query]);
  const save=async()=>{setSaving(true);setError('');try{await adminApi(`/api/access/users/${user.id}`,{method:'PATCH',body:JSON.stringify({access,all_clients:access.all_clients,client_ids:access.all_clients?[]:selected})});onSaved()}catch(e){const m=e instanceof Error?e.message:'Could not save access.';setError(m);toast(m,true)}finally{setSaving(false)}};
  const toggle=(id:number,checked:boolean)=>setSelected(v=>checked?Array.from(new Set([...v,id])):v.filter(x=>x!==id));
  return <Modal onClose={onClose} access><ModalHead title={`Access · ${user.name}`} onClose={onClose}/><div className="il-team-access-guide"><div><strong>Give this person only what they need for their job.</strong><small>{user.email} · {user.role.replaceAll('_',' ')}. Their role sets the maximum permissions; you can narrow them here.</small></div><div className="il-team-flow"><span>1 Account</span><i>→</i><b>2 Access</b><i>→</i><span>3 Ready</span></div></div><div className="il-v4-access-editor"><section><h4>Workspace modules</h4>{MODULES.map(m=><label key={m}><input type="checkbox" checked={!!access[m]} onChange={e=>setAccess({...access,[m]:e.target.checked})}/><span>{MODULE_LABELS[m]}</span></label>)}</section><section><h4>Client visibility</h4><label><input type="checkbox" checked={access.all_clients} onChange={e=>setAccess({...access,all_clients:e.target.checked})}/><span>All clients</span></label>{!access.all_clients&&<><div className="il-access-client-tools"><input className="il-access-client-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search clients…"/><button type="button" onClick={()=>setSelected(clients.map(c=>c.id))}>Select all</button><button type="button" onClick={()=>setSelected([])}>Clear</button></div><div className="il-v4-client-checks">{filtered.map(c=><label key={c.id}><input type="checkbox" checked={selected.includes(c.id)} onChange={e=>toggle(c.id,e.target.checked)}/><span>{c.name}{c.company?` · ${c.company}`:''}</span></label>)}{!filtered.length&&<small>No clients match your search.</small>}</div></>}</section></div>{error&&<div className="il-team-api-error" style={{margin:'8px 26px 0'}}>{error}</div>}<div className="il-v4-modal-actions"><button type="button" className="il-admin-button" onClick={onClose}>Finish later</button><button type="button" className="il-admin-button il-admin-primary" disabled={saving||(!access.all_clients&&selected.length===0)} onClick={()=>void save()}>{saving?'Saving…':<><Check size={15}/> Save access</>}</button></div></Modal>
}
